//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogDetailsInitParameters) DeepCopyInto(out *CatalogDetailsInitParameters) {
	*out = *in
	out.AdminPasswordSecretRef = in.AdminPasswordSecretRef
	if in.CloudAutonomousVMClusterID != nil {
		in, out := &in.CloudAutonomousVMClusterID, &out.CloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
	if in.ComputeCount != nil {
		in, out := &in.ComputeCount, &out.ComputeCount
		*out = new(float64)
		**out = **in
	}
	if in.DataStorageSizeInGbs != nil {
		in, out := &in.DataStorageSizeInGbs, &out.DataStorageSizeInGbs
		*out = new(float64)
		**out = **in
	}
	if in.EncryptionKeyDetails != nil {
		in, out := &in.EncryptionKeyDetails, &out.EncryptionKeyDetails
		*out = make([]EncryptionKeyDetailsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IsAutoScalingEnabled != nil {
		in, out := &in.IsAutoScalingEnabled, &out.IsAutoScalingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PeerCloudAutonomousVMClusterID != nil {
		in, out := &in.PeerCloudAutonomousVMClusterID, &out.PeerCloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogDetailsInitParameters.
func (in *CatalogDetailsInitParameters) DeepCopy() *CatalogDetailsInitParameters {
	if in == nil {
		return nil
	}
	out := new(CatalogDetailsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogDetailsObservation) DeepCopyInto(out *CatalogDetailsObservation) {
	*out = *in
	if in.CloudAutonomousVMClusterID != nil {
		in, out := &in.CloudAutonomousVMClusterID, &out.CloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
	if in.ComputeCount != nil {
		in, out := &in.ComputeCount, &out.ComputeCount
		*out = new(float64)
		**out = **in
	}
	if in.ContainerDatabaseID != nil {
		in, out := &in.ContainerDatabaseID, &out.ContainerDatabaseID
		*out = new(string)
		**out = **in
	}
	if in.ContainerDatabaseParentID != nil {
		in, out := &in.ContainerDatabaseParentID, &out.ContainerDatabaseParentID
		*out = new(string)
		**out = **in
	}
	if in.DataStorageSizeInGbs != nil {
		in, out := &in.DataStorageSizeInGbs, &out.DataStorageSizeInGbs
		*out = new(float64)
		**out = **in
	}
	if in.EncryptionKeyDetails != nil {
		in, out := &in.EncryptionKeyDetails, &out.EncryptionKeyDetails
		*out = make([]EncryptionKeyDetailsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IsAutoScalingEnabled != nil {
		in, out := &in.IsAutoScalingEnabled, &out.IsAutoScalingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PeerCloudAutonomousVMClusterID != nil {
		in, out := &in.PeerCloudAutonomousVMClusterID, &out.PeerCloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
	if in.ShardGroup != nil {
		in, out := &in.ShardGroup, &out.ShardGroup
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.SupportingResourceID != nil {
		in, out := &in.SupportingResourceID, &out.SupportingResourceID
		*out = new(string)
		**out = **in
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeSSLCertificateExpires != nil {
		in, out := &in.TimeSSLCertificateExpires, &out.TimeSSLCertificateExpires
		*out = new(string)
		**out = **in
	}
	if in.TimeUpdated != nil {
		in, out := &in.TimeUpdated, &out.TimeUpdated
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogDetailsObservation.
func (in *CatalogDetailsObservation) DeepCopy() *CatalogDetailsObservation {
	if in == nil {
		return nil
	}
	out := new(CatalogDetailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CatalogDetailsParameters) DeepCopyInto(out *CatalogDetailsParameters) {
	*out = *in
	out.AdminPasswordSecretRef = in.AdminPasswordSecretRef
	if in.CloudAutonomousVMClusterID != nil {
		in, out := &in.CloudAutonomousVMClusterID, &out.CloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
	if in.ComputeCount != nil {
		in, out := &in.ComputeCount, &out.ComputeCount
		*out = new(float64)
		**out = **in
	}
	if in.DataStorageSizeInGbs != nil {
		in, out := &in.DataStorageSizeInGbs, &out.DataStorageSizeInGbs
		*out = new(float64)
		**out = **in
	}
	if in.EncryptionKeyDetails != nil {
		in, out := &in.EncryptionKeyDetails, &out.EncryptionKeyDetails
		*out = make([]EncryptionKeyDetailsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IsAutoScalingEnabled != nil {
		in, out := &in.IsAutoScalingEnabled, &out.IsAutoScalingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PeerCloudAutonomousVMClusterID != nil {
		in, out := &in.PeerCloudAutonomousVMClusterID, &out.PeerCloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CatalogDetailsParameters.
func (in *CatalogDetailsParameters) DeepCopy() *CatalogDetailsParameters {
	if in == nil {
		return nil
	}
	out := new(CatalogDetailsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionStringsInitParameters) DeepCopyInto(out *ConnectionStringsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStringsInitParameters.
func (in *ConnectionStringsInitParameters) DeepCopy() *ConnectionStringsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConnectionStringsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionStringsObservation) DeepCopyInto(out *ConnectionStringsObservation) {
	*out = *in
	if in.AllConnectionStrings != nil {
		in, out := &in.AllConnectionStrings, &out.AllConnectionStrings
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStringsObservation.
func (in *ConnectionStringsObservation) DeepCopy() *ConnectionStringsObservation {
	if in == nil {
		return nil
	}
	out := new(ConnectionStringsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionStringsParameters) DeepCopyInto(out *ConnectionStringsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStringsParameters.
func (in *ConnectionStringsParameters) DeepCopy() *ConnectionStringsParameters {
	if in == nil {
		return nil
	}
	out := new(ConnectionStringsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpoint) DeepCopyInto(out *DistributedDatabasePrivateEndpoint) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpoint.
func (in *DistributedDatabasePrivateEndpoint) DeepCopy() *DistributedDatabasePrivateEndpoint {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedDatabasePrivateEndpoint) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpointInitParameters) DeepCopyInto(out *DistributedDatabasePrivateEndpointInitParameters) {
	*out = *in
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ReinstateProxyInstanceTrigger != nil {
		in, out := &in.ReinstateProxyInstanceTrigger, &out.ReinstateProxyInstanceTrigger
		*out = new(float64)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpointInitParameters.
func (in *DistributedDatabasePrivateEndpointInitParameters) DeepCopy() *DistributedDatabasePrivateEndpointInitParameters {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpointInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpointList) DeepCopyInto(out *DistributedDatabasePrivateEndpointList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DistributedDatabasePrivateEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpointList.
func (in *DistributedDatabasePrivateEndpointList) DeepCopy() *DistributedDatabasePrivateEndpointList {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpointList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedDatabasePrivateEndpointList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpointObservation) DeepCopyInto(out *DistributedDatabasePrivateEndpointObservation) {
	*out = *in
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LifecycleStateDetails != nil {
		in, out := &in.LifecycleStateDetails, &out.LifecycleStateDetails
		*out = new(string)
		**out = **in
	}
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PrivateIP != nil {
		in, out := &in.PrivateIP, &out.PrivateIP
		*out = new(string)
		**out = **in
	}
	if in.ProxyComputeInstanceID != nil {
		in, out := &in.ProxyComputeInstanceID, &out.ProxyComputeInstanceID
		*out = new(string)
		**out = **in
	}
	if in.ReinstateProxyInstanceTrigger != nil {
		in, out := &in.ReinstateProxyInstanceTrigger, &out.ReinstateProxyInstanceTrigger
		*out = new(float64)
		**out = **in
	}
	if in.ShardedDatabases != nil {
		in, out := &in.ShardedDatabases, &out.ShardedDatabases
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeUpdated != nil {
		in, out := &in.TimeUpdated, &out.TimeUpdated
		*out = new(string)
		**out = **in
	}
	if in.VcnID != nil {
		in, out := &in.VcnID, &out.VcnID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpointObservation.
func (in *DistributedDatabasePrivateEndpointObservation) DeepCopy() *DistributedDatabasePrivateEndpointObservation {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpointObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpointParameters) DeepCopyInto(out *DistributedDatabasePrivateEndpointParameters) {
	*out = *in
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.NsgIds != nil {
		in, out := &in.NsgIds, &out.NsgIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ReinstateProxyInstanceTrigger != nil {
		in, out := &in.ReinstateProxyInstanceTrigger, &out.ReinstateProxyInstanceTrigger
		*out = new(float64)
		**out = **in
	}
	if in.SubnetID != nil {
		in, out := &in.SubnetID, &out.SubnetID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpointParameters.
func (in *DistributedDatabasePrivateEndpointParameters) DeepCopy() *DistributedDatabasePrivateEndpointParameters {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpointParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpointSpec) DeepCopyInto(out *DistributedDatabasePrivateEndpointSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpointSpec.
func (in *DistributedDatabasePrivateEndpointSpec) DeepCopy() *DistributedDatabasePrivateEndpointSpec {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpointSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabasePrivateEndpointStatus) DeepCopyInto(out *DistributedDatabasePrivateEndpointStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabasePrivateEndpointStatus.
func (in *DistributedDatabasePrivateEndpointStatus) DeepCopy() *DistributedDatabasePrivateEndpointStatus {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabasePrivateEndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardedDatabase) DeepCopyInto(out *DistributedDatabaseShardedDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardedDatabase.
func (in *DistributedDatabaseShardedDatabase) DeepCopy() *DistributedDatabaseShardedDatabase {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardedDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedDatabaseShardedDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardedDatabaseInitParameters) DeepCopyInto(out *DistributedDatabaseShardedDatabaseInitParameters) {
	*out = *in
	if in.CASignedCertificate != nil {
		in, out := &in.CASignedCertificate, &out.CASignedCertificate
		*out = new(string)
		**out = **in
	}
	if in.CatalogDetails != nil {
		in, out := &in.CatalogDetails, &out.CatalogDetails
		*out = make([]CatalogDetailsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CharacterSet != nil {
		in, out := &in.CharacterSet, &out.CharacterSet
		*out = new(string)
		**out = **in
	}
	if in.Chunks != nil {
		in, out := &in.Chunks, &out.Chunks
		*out = new(float64)
		**out = **in
	}
	if in.ClusterCertificateCommonName != nil {
		in, out := &in.ClusterCertificateCommonName, &out.ClusterCertificateCommonName
		*out = new(string)
		**out = **in
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ConfigureGsmsTrigger != nil {
		in, out := &in.ConfigureGsmsTrigger, &out.ConfigureGsmsTrigger
		*out = new(float64)
		**out = **in
	}
	if in.ConfigureGsmsTriggerIsLatestGsmImage != nil {
		in, out := &in.ConfigureGsmsTriggerIsLatestGsmImage, &out.ConfigureGsmsTriggerIsLatestGsmImage
		*out = new(bool)
		**out = **in
	}
	if in.ConfigureGsmsTriggerOldGsmNames != nil {
		in, out := &in.ConfigureGsmsTriggerOldGsmNames, &out.ConfigureGsmsTriggerOldGsmNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ConfigureShardingTrigger != nil {
		in, out := &in.ConfigureShardingTrigger, &out.ConfigureShardingTrigger
		*out = new(float64)
		**out = **in
	}
	if in.DBDeploymentType != nil {
		in, out := &in.DBDeploymentType, &out.DBDeploymentType
		*out = new(string)
		**out = **in
	}
	if in.DBVersion != nil {
		in, out := &in.DBVersion, &out.DBVersion
		*out = new(string)
		**out = **in
	}
	if in.DBWorkload != nil {
		in, out := &in.DBWorkload, &out.DBWorkload
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DownloadGsmCertificateSigningRequestTrigger != nil {
		in, out := &in.DownloadGsmCertificateSigningRequestTrigger, &out.DownloadGsmCertificateSigningRequestTrigger
		*out = new(float64)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.GenerateGsmCertificateSigningRequestTrigger != nil {
		in, out := &in.GenerateGsmCertificateSigningRequestTrigger, &out.GenerateGsmCertificateSigningRequestTrigger
		*out = new(float64)
		**out = **in
	}
	if in.GenerateWalletPasswordSecretRef != nil {
		in, out := &in.GenerateWalletPasswordSecretRef, &out.GenerateWalletPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.GenerateWalletTrigger != nil {
		in, out := &in.GenerateWalletTrigger, &out.GenerateWalletTrigger
		*out = new(float64)
		**out = **in
	}
	if in.GetConnectionStringTrigger != nil {
		in, out := &in.GetConnectionStringTrigger, &out.GetConnectionStringTrigger
		*out = new(float64)
		**out = **in
	}
	if in.ListenerPort != nil {
		in, out := &in.ListenerPort, &out.ListenerPort
		*out = new(float64)
		**out = **in
	}
	if in.ListenerPortTLS != nil {
		in, out := &in.ListenerPortTLS, &out.ListenerPortTLS
		*out = new(float64)
		**out = **in
	}
	if in.NcharacterSet != nil {
		in, out := &in.NcharacterSet, &out.NcharacterSet
		*out = new(string)
		**out = **in
	}
	if in.OnsPortLocal != nil {
		in, out := &in.OnsPortLocal, &out.OnsPortLocal
		*out = new(float64)
		**out = **in
	}
	if in.OnsPortRemote != nil {
		in, out := &in.OnsPortRemote, &out.OnsPortRemote
		*out = new(float64)
		**out = **in
	}
	if in.PatchOperations != nil {
		in, out := &in.PatchOperations, &out.PatchOperations
		*out = make([]PatchOperationsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.ReplicationFactor != nil {
		in, out := &in.ReplicationFactor, &out.ReplicationFactor
		*out = new(float64)
		**out = **in
	}
	if in.ReplicationMethod != nil {
		in, out := &in.ReplicationMethod, &out.ReplicationMethod
		*out = new(string)
		**out = **in
	}
	if in.ReplicationUnit != nil {
		in, out := &in.ReplicationUnit, &out.ReplicationUnit
		*out = new(float64)
		**out = **in
	}
	if in.ShardDetails != nil {
		in, out := &in.ShardDetails, &out.ShardDetails
		*out = make([]ShardDetailsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ShardingMethod != nil {
		in, out := &in.ShardingMethod, &out.ShardingMethod
		*out = new(string)
		**out = **in
	}
	if in.StartDatabaseTrigger != nil {
		in, out := &in.StartDatabaseTrigger, &out.StartDatabaseTrigger
		*out = new(float64)
		**out = **in
	}
	if in.StopDatabaseTrigger != nil {
		in, out := &in.StopDatabaseTrigger, &out.StopDatabaseTrigger
		*out = new(float64)
		**out = **in
	}
	if in.UploadSignedCertificateAndGenerateWalletTrigger != nil {
		in, out := &in.UploadSignedCertificateAndGenerateWalletTrigger, &out.UploadSignedCertificateAndGenerateWalletTrigger
		*out = new(float64)
		**out = **in
	}
	if in.ValidateNetworkTrigger != nil {
		in, out := &in.ValidateNetworkTrigger, &out.ValidateNetworkTrigger
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardedDatabaseInitParameters.
func (in *DistributedDatabaseShardedDatabaseInitParameters) DeepCopy() *DistributedDatabaseShardedDatabaseInitParameters {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardedDatabaseInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardedDatabaseList) DeepCopyInto(out *DistributedDatabaseShardedDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DistributedDatabaseShardedDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardedDatabaseList.
func (in *DistributedDatabaseShardedDatabaseList) DeepCopy() *DistributedDatabaseShardedDatabaseList {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardedDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DistributedDatabaseShardedDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardedDatabaseObservation) DeepCopyInto(out *DistributedDatabaseShardedDatabaseObservation) {
	*out = *in
	if in.CASignedCertificate != nil {
		in, out := &in.CASignedCertificate, &out.CASignedCertificate
		*out = new(string)
		**out = **in
	}
	if in.CatalogDetails != nil {
		in, out := &in.CatalogDetails, &out.CatalogDetails
		*out = make([]CatalogDetailsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CharacterSet != nil {
		in, out := &in.CharacterSet, &out.CharacterSet
		*out = new(string)
		**out = **in
	}
	if in.Chunks != nil {
		in, out := &in.Chunks, &out.Chunks
		*out = new(float64)
		**out = **in
	}
	if in.ClusterCertificateCommonName != nil {
		in, out := &in.ClusterCertificateCommonName, &out.ClusterCertificateCommonName
		*out = new(string)
		**out = **in
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ConfigureGsmsTrigger != nil {
		in, out := &in.ConfigureGsmsTrigger, &out.ConfigureGsmsTrigger
		*out = new(float64)
		**out = **in
	}
	if in.ConfigureGsmsTriggerIsLatestGsmImage != nil {
		in, out := &in.ConfigureGsmsTriggerIsLatestGsmImage, &out.ConfigureGsmsTriggerIsLatestGsmImage
		*out = new(bool)
		**out = **in
	}
	if in.ConfigureGsmsTriggerOldGsmNames != nil {
		in, out := &in.ConfigureGsmsTriggerOldGsmNames, &out.ConfigureGsmsTriggerOldGsmNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ConfigureShardingTrigger != nil {
		in, out := &in.ConfigureShardingTrigger, &out.ConfigureShardingTrigger
		*out = new(float64)
		**out = **in
	}
	if in.ConnectionStrings != nil {
		in, out := &in.ConnectionStrings, &out.ConnectionStrings
		*out = make([]ConnectionStringsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DBDeploymentType != nil {
		in, out := &in.DBDeploymentType, &out.DBDeploymentType
		*out = new(string)
		**out = **in
	}
	if in.DBVersion != nil {
		in, out := &in.DBVersion, &out.DBVersion
		*out = new(string)
		**out = **in
	}
	if in.DBWorkload != nil {
		in, out := &in.DBWorkload, &out.DBWorkload
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DownloadGsmCertificateSigningRequestTrigger != nil {
		in, out := &in.DownloadGsmCertificateSigningRequestTrigger, &out.DownloadGsmCertificateSigningRequestTrigger
		*out = new(float64)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.GenerateGsmCertificateSigningRequestTrigger != nil {
		in, out := &in.GenerateGsmCertificateSigningRequestTrigger, &out.GenerateGsmCertificateSigningRequestTrigger
		*out = new(float64)
		**out = **in
	}
	if in.GenerateWalletTrigger != nil {
		in, out := &in.GenerateWalletTrigger, &out.GenerateWalletTrigger
		*out = new(float64)
		**out = **in
	}
	if in.GetConnectionStringTrigger != nil {
		in, out := &in.GetConnectionStringTrigger, &out.GetConnectionStringTrigger
		*out = new(float64)
		**out = **in
	}
	if in.Gsms != nil {
		in, out := &in.Gsms, &out.Gsms
		*out = make([]GsmsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LifecycleState != nil {
		in, out := &in.LifecycleState, &out.LifecycleState
		*out = new(string)
		**out = **in
	}
	if in.LifecycleStateDetails != nil {
		in, out := &in.LifecycleStateDetails, &out.LifecycleStateDetails
		*out = new(string)
		**out = **in
	}
	if in.ListenerPort != nil {
		in, out := &in.ListenerPort, &out.ListenerPort
		*out = new(float64)
		**out = **in
	}
	if in.ListenerPortTLS != nil {
		in, out := &in.ListenerPortTLS, &out.ListenerPortTLS
		*out = new(float64)
		**out = **in
	}
	if in.NcharacterSet != nil {
		in, out := &in.NcharacterSet, &out.NcharacterSet
		*out = new(string)
		**out = **in
	}
	if in.OnsPortLocal != nil {
		in, out := &in.OnsPortLocal, &out.OnsPortLocal
		*out = new(float64)
		**out = **in
	}
	if in.OnsPortRemote != nil {
		in, out := &in.OnsPortRemote, &out.OnsPortRemote
		*out = new(float64)
		**out = **in
	}
	if in.PatchOperations != nil {
		in, out := &in.PatchOperations, &out.PatchOperations
		*out = make([]PatchOperationsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.PrivateEndpoint != nil {
		in, out := &in.PrivateEndpoint, &out.PrivateEndpoint
		*out = new(string)
		**out = **in
	}
	if in.ReplicationFactor != nil {
		in, out := &in.ReplicationFactor, &out.ReplicationFactor
		*out = new(float64)
		**out = **in
	}
	if in.ReplicationMethod != nil {
		in, out := &in.ReplicationMethod, &out.ReplicationMethod
		*out = new(string)
		**out = **in
	}
	if in.ReplicationUnit != nil {
		in, out := &in.ReplicationUnit, &out.ReplicationUnit
		*out = new(float64)
		**out = **in
	}
	if in.ShardDetails != nil {
		in, out := &in.ShardDetails, &out.ShardDetails
		*out = make([]ShardDetailsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ShardedDatabaseID != nil {
		in, out := &in.ShardedDatabaseID, &out.ShardedDatabaseID
		*out = new(string)
		**out = **in
	}
	if in.ShardingMethod != nil {
		in, out := &in.ShardingMethod, &out.ShardingMethod
		*out = new(string)
		**out = **in
	}
	if in.StartDatabaseTrigger != nil {
		in, out := &in.StartDatabaseTrigger, &out.StartDatabaseTrigger
		*out = new(float64)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.StopDatabaseTrigger != nil {
		in, out := &in.StopDatabaseTrigger, &out.StopDatabaseTrigger
		*out = new(float64)
		**out = **in
	}
	if in.SystemTags != nil {
		in, out := &in.SystemTags, &out.SystemTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeUpdated != nil {
		in, out := &in.TimeUpdated, &out.TimeUpdated
		*out = new(string)
		**out = **in
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
	if in.UploadSignedCertificateAndGenerateWalletTrigger != nil {
		in, out := &in.UploadSignedCertificateAndGenerateWalletTrigger, &out.UploadSignedCertificateAndGenerateWalletTrigger
		*out = new(float64)
		**out = **in
	}
	if in.ValidateNetworkTrigger != nil {
		in, out := &in.ValidateNetworkTrigger, &out.ValidateNetworkTrigger
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardedDatabaseObservation.
func (in *DistributedDatabaseShardedDatabaseObservation) DeepCopy() *DistributedDatabaseShardedDatabaseObservation {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardedDatabaseObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardedDatabaseParameters) DeepCopyInto(out *DistributedDatabaseShardedDatabaseParameters) {
	*out = *in
	if in.CASignedCertificate != nil {
		in, out := &in.CASignedCertificate, &out.CASignedCertificate
		*out = new(string)
		**out = **in
	}
	if in.CatalogDetails != nil {
		in, out := &in.CatalogDetails, &out.CatalogDetails
		*out = make([]CatalogDetailsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CharacterSet != nil {
		in, out := &in.CharacterSet, &out.CharacterSet
		*out = new(string)
		**out = **in
	}
	if in.Chunks != nil {
		in, out := &in.Chunks, &out.Chunks
		*out = new(float64)
		**out = **in
	}
	if in.ClusterCertificateCommonName != nil {
		in, out := &in.ClusterCertificateCommonName, &out.ClusterCertificateCommonName
		*out = new(string)
		**out = **in
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ConfigureGsmsTrigger != nil {
		in, out := &in.ConfigureGsmsTrigger, &out.ConfigureGsmsTrigger
		*out = new(float64)
		**out = **in
	}
	if in.ConfigureGsmsTriggerIsLatestGsmImage != nil {
		in, out := &in.ConfigureGsmsTriggerIsLatestGsmImage, &out.ConfigureGsmsTriggerIsLatestGsmImage
		*out = new(bool)
		**out = **in
	}
	if in.ConfigureGsmsTriggerOldGsmNames != nil {
		in, out := &in.ConfigureGsmsTriggerOldGsmNames, &out.ConfigureGsmsTriggerOldGsmNames
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ConfigureShardingTrigger != nil {
		in, out := &in.ConfigureShardingTrigger, &out.ConfigureShardingTrigger
		*out = new(float64)
		**out = **in
	}
	if in.DBDeploymentType != nil {
		in, out := &in.DBDeploymentType, &out.DBDeploymentType
		*out = new(string)
		**out = **in
	}
	if in.DBVersion != nil {
		in, out := &in.DBVersion, &out.DBVersion
		*out = new(string)
		**out = **in
	}
	if in.DBWorkload != nil {
		in, out := &in.DBWorkload, &out.DBWorkload
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.DownloadGsmCertificateSigningRequestTrigger != nil {
		in, out := &in.DownloadGsmCertificateSigningRequestTrigger, &out.DownloadGsmCertificateSigningRequestTrigger
		*out = new(float64)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.GenerateGsmCertificateSigningRequestTrigger != nil {
		in, out := &in.GenerateGsmCertificateSigningRequestTrigger, &out.GenerateGsmCertificateSigningRequestTrigger
		*out = new(float64)
		**out = **in
	}
	if in.GenerateWalletPasswordSecretRef != nil {
		in, out := &in.GenerateWalletPasswordSecretRef, &out.GenerateWalletPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.GenerateWalletTrigger != nil {
		in, out := &in.GenerateWalletTrigger, &out.GenerateWalletTrigger
		*out = new(float64)
		**out = **in
	}
	if in.GetConnectionStringTrigger != nil {
		in, out := &in.GetConnectionStringTrigger, &out.GetConnectionStringTrigger
		*out = new(float64)
		**out = **in
	}
	if in.ListenerPort != nil {
		in, out := &in.ListenerPort, &out.ListenerPort
		*out = new(float64)
		**out = **in
	}
	if in.ListenerPortTLS != nil {
		in, out := &in.ListenerPortTLS, &out.ListenerPortTLS
		*out = new(float64)
		**out = **in
	}
	if in.NcharacterSet != nil {
		in, out := &in.NcharacterSet, &out.NcharacterSet
		*out = new(string)
		**out = **in
	}
	if in.OnsPortLocal != nil {
		in, out := &in.OnsPortLocal, &out.OnsPortLocal
		*out = new(float64)
		**out = **in
	}
	if in.OnsPortRemote != nil {
		in, out := &in.OnsPortRemote, &out.OnsPortRemote
		*out = new(float64)
		**out = **in
	}
	if in.PatchOperations != nil {
		in, out := &in.PatchOperations, &out.PatchOperations
		*out = make([]PatchOperationsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Prefix != nil {
		in, out := &in.Prefix, &out.Prefix
		*out = new(string)
		**out = **in
	}
	if in.ReplicationFactor != nil {
		in, out := &in.ReplicationFactor, &out.ReplicationFactor
		*out = new(float64)
		**out = **in
	}
	if in.ReplicationMethod != nil {
		in, out := &in.ReplicationMethod, &out.ReplicationMethod
		*out = new(string)
		**out = **in
	}
	if in.ReplicationUnit != nil {
		in, out := &in.ReplicationUnit, &out.ReplicationUnit
		*out = new(float64)
		**out = **in
	}
	if in.ShardDetails != nil {
		in, out := &in.ShardDetails, &out.ShardDetails
		*out = make([]ShardDetailsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ShardingMethod != nil {
		in, out := &in.ShardingMethod, &out.ShardingMethod
		*out = new(string)
		**out = **in
	}
	if in.StartDatabaseTrigger != nil {
		in, out := &in.StartDatabaseTrigger, &out.StartDatabaseTrigger
		*out = new(float64)
		**out = **in
	}
	if in.StopDatabaseTrigger != nil {
		in, out := &in.StopDatabaseTrigger, &out.StopDatabaseTrigger
		*out = new(float64)
		**out = **in
	}
	if in.UploadSignedCertificateAndGenerateWalletTrigger != nil {
		in, out := &in.UploadSignedCertificateAndGenerateWalletTrigger, &out.UploadSignedCertificateAndGenerateWalletTrigger
		*out = new(float64)
		**out = **in
	}
	if in.ValidateNetworkTrigger != nil {
		in, out := &in.ValidateNetworkTrigger, &out.ValidateNetworkTrigger
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardedDatabaseParameters.
func (in *DistributedDatabaseShardedDatabaseParameters) DeepCopy() *DistributedDatabaseShardedDatabaseParameters {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardedDatabaseParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardedDatabaseSpec) DeepCopyInto(out *DistributedDatabaseShardedDatabaseSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardedDatabaseSpec.
func (in *DistributedDatabaseShardedDatabaseSpec) DeepCopy() *DistributedDatabaseShardedDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardedDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DistributedDatabaseShardedDatabaseStatus) DeepCopyInto(out *DistributedDatabaseShardedDatabaseStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DistributedDatabaseShardedDatabaseStatus.
func (in *DistributedDatabaseShardedDatabaseStatus) DeepCopy() *DistributedDatabaseShardedDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(DistributedDatabaseShardedDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionKeyDetailsInitParameters) DeepCopyInto(out *EncryptionKeyDetailsInitParameters) {
	*out = *in
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyVersionID != nil {
		in, out := &in.KMSKeyVersionID, &out.KMSKeyVersionID
		*out = new(string)
		**out = **in
	}
	if in.VaultID != nil {
		in, out := &in.VaultID, &out.VaultID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionKeyDetailsInitParameters.
func (in *EncryptionKeyDetailsInitParameters) DeepCopy() *EncryptionKeyDetailsInitParameters {
	if in == nil {
		return nil
	}
	out := new(EncryptionKeyDetailsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionKeyDetailsObservation) DeepCopyInto(out *EncryptionKeyDetailsObservation) {
	*out = *in
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyVersionID != nil {
		in, out := &in.KMSKeyVersionID, &out.KMSKeyVersionID
		*out = new(string)
		**out = **in
	}
	if in.VaultID != nil {
		in, out := &in.VaultID, &out.VaultID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionKeyDetailsObservation.
func (in *EncryptionKeyDetailsObservation) DeepCopy() *EncryptionKeyDetailsObservation {
	if in == nil {
		return nil
	}
	out := new(EncryptionKeyDetailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptionKeyDetailsParameters) DeepCopyInto(out *EncryptionKeyDetailsParameters) {
	*out = *in
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyVersionID != nil {
		in, out := &in.KMSKeyVersionID, &out.KMSKeyVersionID
		*out = new(string)
		**out = **in
	}
	if in.VaultID != nil {
		in, out := &in.VaultID, &out.VaultID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptionKeyDetailsParameters.
func (in *EncryptionKeyDetailsParameters) DeepCopy() *EncryptionKeyDetailsParameters {
	if in == nil {
		return nil
	}
	out := new(EncryptionKeyDetailsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GsmsInitParameters) DeepCopyInto(out *GsmsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GsmsInitParameters.
func (in *GsmsInitParameters) DeepCopy() *GsmsInitParameters {
	if in == nil {
		return nil
	}
	out := new(GsmsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GsmsObservation) DeepCopyInto(out *GsmsObservation) {
	*out = *in
	if in.ComputeCount != nil {
		in, out := &in.ComputeCount, &out.ComputeCount
		*out = new(float64)
		**out = **in
	}
	if in.DataStorageSizeInGbs != nil {
		in, out := &in.DataStorageSizeInGbs, &out.DataStorageSizeInGbs
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.SupportingResourceID != nil {
		in, out := &in.SupportingResourceID, &out.SupportingResourceID
		*out = new(string)
		**out = **in
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeSSLCertificateExpires != nil {
		in, out := &in.TimeSSLCertificateExpires, &out.TimeSSLCertificateExpires
		*out = new(string)
		**out = **in
	}
	if in.TimeUpdated != nil {
		in, out := &in.TimeUpdated, &out.TimeUpdated
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GsmsObservation.
func (in *GsmsObservation) DeepCopy() *GsmsObservation {
	if in == nil {
		return nil
	}
	out := new(GsmsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GsmsParameters) DeepCopyInto(out *GsmsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GsmsParameters.
func (in *GsmsParameters) DeepCopy() *GsmsParameters {
	if in == nil {
		return nil
	}
	out := new(GsmsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchOperationsInitParameters) DeepCopyInto(out *PatchOperationsInitParameters) {
	*out = *in
	if in.Operation != nil {
		in, out := &in.Operation, &out.Operation
		*out = new(string)
		**out = **in
	}
	if in.Selection != nil {
		in, out := &in.Selection, &out.Selection
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchOperationsInitParameters.
func (in *PatchOperationsInitParameters) DeepCopy() *PatchOperationsInitParameters {
	if in == nil {
		return nil
	}
	out := new(PatchOperationsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchOperationsObservation) DeepCopyInto(out *PatchOperationsObservation) {
	*out = *in
	if in.Operation != nil {
		in, out := &in.Operation, &out.Operation
		*out = new(string)
		**out = **in
	}
	if in.Selection != nil {
		in, out := &in.Selection, &out.Selection
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchOperationsObservation.
func (in *PatchOperationsObservation) DeepCopy() *PatchOperationsObservation {
	if in == nil {
		return nil
	}
	out := new(PatchOperationsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PatchOperationsParameters) DeepCopyInto(out *PatchOperationsParameters) {
	*out = *in
	if in.Operation != nil {
		in, out := &in.Operation, &out.Operation
		*out = new(string)
		**out = **in
	}
	if in.Selection != nil {
		in, out := &in.Selection, &out.Selection
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PatchOperationsParameters.
func (in *PatchOperationsParameters) DeepCopy() *PatchOperationsParameters {
	if in == nil {
		return nil
	}
	out := new(PatchOperationsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardDetailsEncryptionKeyDetailsInitParameters) DeepCopyInto(out *ShardDetailsEncryptionKeyDetailsInitParameters) {
	*out = *in
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyVersionID != nil {
		in, out := &in.KMSKeyVersionID, &out.KMSKeyVersionID
		*out = new(string)
		**out = **in
	}
	if in.VaultID != nil {
		in, out := &in.VaultID, &out.VaultID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardDetailsEncryptionKeyDetailsInitParameters.
func (in *ShardDetailsEncryptionKeyDetailsInitParameters) DeepCopy() *ShardDetailsEncryptionKeyDetailsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ShardDetailsEncryptionKeyDetailsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardDetailsEncryptionKeyDetailsObservation) DeepCopyInto(out *ShardDetailsEncryptionKeyDetailsObservation) {
	*out = *in
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyVersionID != nil {
		in, out := &in.KMSKeyVersionID, &out.KMSKeyVersionID
		*out = new(string)
		**out = **in
	}
	if in.VaultID != nil {
		in, out := &in.VaultID, &out.VaultID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardDetailsEncryptionKeyDetailsObservation.
func (in *ShardDetailsEncryptionKeyDetailsObservation) DeepCopy() *ShardDetailsEncryptionKeyDetailsObservation {
	if in == nil {
		return nil
	}
	out := new(ShardDetailsEncryptionKeyDetailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardDetailsEncryptionKeyDetailsParameters) DeepCopyInto(out *ShardDetailsEncryptionKeyDetailsParameters) {
	*out = *in
	if in.KMSKeyID != nil {
		in, out := &in.KMSKeyID, &out.KMSKeyID
		*out = new(string)
		**out = **in
	}
	if in.KMSKeyVersionID != nil {
		in, out := &in.KMSKeyVersionID, &out.KMSKeyVersionID
		*out = new(string)
		**out = **in
	}
	if in.VaultID != nil {
		in, out := &in.VaultID, &out.VaultID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardDetailsEncryptionKeyDetailsParameters.
func (in *ShardDetailsEncryptionKeyDetailsParameters) DeepCopy() *ShardDetailsEncryptionKeyDetailsParameters {
	if in == nil {
		return nil
	}
	out := new(ShardDetailsEncryptionKeyDetailsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardDetailsInitParameters) DeepCopyInto(out *ShardDetailsInitParameters) {
	*out = *in
	out.AdminPasswordSecretRef = in.AdminPasswordSecretRef
	if in.CloudAutonomousVMClusterID != nil {
		in, out := &in.CloudAutonomousVMClusterID, &out.CloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
	if in.ComputeCount != nil {
		in, out := &in.ComputeCount, &out.ComputeCount
		*out = new(float64)
		**out = **in
	}
	if in.DataStorageSizeInGbs != nil {
		in, out := &in.DataStorageSizeInGbs, &out.DataStorageSizeInGbs
		*out = new(float64)
		**out = **in
	}
	if in.EncryptionKeyDetails != nil {
		in, out := &in.EncryptionKeyDetails, &out.EncryptionKeyDetails
		*out = make([]ShardDetailsEncryptionKeyDetailsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IsAutoScalingEnabled != nil {
		in, out := &in.IsAutoScalingEnabled, &out.IsAutoScalingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PeerCloudAutonomousVMClusterID != nil {
		in, out := &in.PeerCloudAutonomousVMClusterID, &out.PeerCloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
	if in.ShardSpace != nil {
		in, out := &in.ShardSpace, &out.ShardSpace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardDetailsInitParameters.
func (in *ShardDetailsInitParameters) DeepCopy() *ShardDetailsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ShardDetailsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardDetailsObservation) DeepCopyInto(out *ShardDetailsObservation) {
	*out = *in
	if in.CloudAutonomousVMClusterID != nil {
		in, out := &in.CloudAutonomousVMClusterID, &out.CloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
	if in.ComputeCount != nil {
		in, out := &in.ComputeCount, &out.ComputeCount
		*out = new(float64)
		**out = **in
	}
	if in.ContainerDatabaseID != nil {
		in, out := &in.ContainerDatabaseID, &out.ContainerDatabaseID
		*out = new(string)
		**out = **in
	}
	if in.ContainerDatabaseParentID != nil {
		in, out := &in.ContainerDatabaseParentID, &out.ContainerDatabaseParentID
		*out = new(string)
		**out = **in
	}
	if in.DataStorageSizeInGbs != nil {
		in, out := &in.DataStorageSizeInGbs, &out.DataStorageSizeInGbs
		*out = new(float64)
		**out = **in
	}
	if in.EncryptionKeyDetails != nil {
		in, out := &in.EncryptionKeyDetails, &out.EncryptionKeyDetails
		*out = make([]ShardDetailsEncryptionKeyDetailsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IsAutoScalingEnabled != nil {
		in, out := &in.IsAutoScalingEnabled, &out.IsAutoScalingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PeerCloudAutonomousVMClusterID != nil {
		in, out := &in.PeerCloudAutonomousVMClusterID, &out.PeerCloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
	if in.ShardGroup != nil {
		in, out := &in.ShardGroup, &out.ShardGroup
		*out = new(string)
		**out = **in
	}
	if in.ShardSpace != nil {
		in, out := &in.ShardSpace, &out.ShardSpace
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.SupportingResourceID != nil {
		in, out := &in.SupportingResourceID, &out.SupportingResourceID
		*out = new(string)
		**out = **in
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeSSLCertificateExpires != nil {
		in, out := &in.TimeSSLCertificateExpires, &out.TimeSSLCertificateExpires
		*out = new(string)
		**out = **in
	}
	if in.TimeUpdated != nil {
		in, out := &in.TimeUpdated, &out.TimeUpdated
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardDetailsObservation.
func (in *ShardDetailsObservation) DeepCopy() *ShardDetailsObservation {
	if in == nil {
		return nil
	}
	out := new(ShardDetailsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShardDetailsParameters) DeepCopyInto(out *ShardDetailsParameters) {
	*out = *in
	out.AdminPasswordSecretRef = in.AdminPasswordSecretRef
	if in.CloudAutonomousVMClusterID != nil {
		in, out := &in.CloudAutonomousVMClusterID, &out.CloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
	if in.ComputeCount != nil {
		in, out := &in.ComputeCount, &out.ComputeCount
		*out = new(float64)
		**out = **in
	}
	if in.DataStorageSizeInGbs != nil {
		in, out := &in.DataStorageSizeInGbs, &out.DataStorageSizeInGbs
		*out = new(float64)
		**out = **in
	}
	if in.EncryptionKeyDetails != nil {
		in, out := &in.EncryptionKeyDetails, &out.EncryptionKeyDetails
		*out = make([]ShardDetailsEncryptionKeyDetailsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IsAutoScalingEnabled != nil {
		in, out := &in.IsAutoScalingEnabled, &out.IsAutoScalingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PeerCloudAutonomousVMClusterID != nil {
		in, out := &in.PeerCloudAutonomousVMClusterID, &out.PeerCloudAutonomousVMClusterID
		*out = new(string)
		**out = **in
	}
	if in.ShardSpace != nil {
		in, out := &in.ShardSpace, &out.ShardSpace
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShardDetailsParameters.
func (in *ShardDetailsParameters) DeepCopy() *ShardDetailsParameters {
	if in == nil {
		return nil
	}
	out := new(ShardDetailsParameters)
	in.DeepCopyInto(out)
	return out
}
