/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PrivateEndpointAttachmentInitParameters struct {

	// The OCID of the attached ODA Instance.
	OdaInstanceID *string `json:"odaInstanceId,omitempty" tf:"oda_instance_id,omitempty"`

	// The OCID of the ODA Private Endpoint.
	OdaPrivateEndpointID *string `json:"odaPrivateEndpointId,omitempty" tf:"oda_private_endpoint_id,omitempty"`
}

type PrivateEndpointAttachmentObservation struct {

	// The OCID of the compartment that the ODA private endpoint attachment belongs to.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// The OCID of the ODA Private Endpoint Attachment.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the attached ODA Instance.
	OdaInstanceID *string `json:"odaInstanceId,omitempty" tf:"oda_instance_id,omitempty"`

	// The OCID of the ODA Private Endpoint.
	OdaPrivateEndpointID *string `json:"odaPrivateEndpointId,omitempty" tf:"oda_private_endpoint_id,omitempty"`

	// The current state of the ODA Private Endpoint attachment.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// When the resource was created. A date-time string as described in RFC 3339, section 14.29.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// When the resource was last updated. A date-time string as described in RFC 3339, section 14.29.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type PrivateEndpointAttachmentParameters struct {

	// The OCID of the attached ODA Instance.
	// +kubebuilder:validation:Optional
	OdaInstanceID *string `json:"odaInstanceId,omitempty" tf:"oda_instance_id,omitempty"`

	// The OCID of the ODA Private Endpoint.
	// +kubebuilder:validation:Optional
	OdaPrivateEndpointID *string `json:"odaPrivateEndpointId,omitempty" tf:"oda_private_endpoint_id,omitempty"`
}

// PrivateEndpointAttachmentSpec defines the desired state of PrivateEndpointAttachment
type PrivateEndpointAttachmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PrivateEndpointAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PrivateEndpointAttachmentInitParameters `json:"initProvider,omitempty"`
}

// PrivateEndpointAttachmentStatus defines the observed state of PrivateEndpointAttachment.
type PrivateEndpointAttachmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PrivateEndpointAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PrivateEndpointAttachment is the Schema for the PrivateEndpointAttachments API. Provides the Oda Private Endpoint Attachment resource in Oracle Cloud Infrastructure Digital Assistant service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type PrivateEndpointAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.odaInstanceId) || (has(self.initProvider) && has(self.initProvider.odaInstanceId))",message="spec.forProvider.odaInstanceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.odaPrivateEndpointId) || (has(self.initProvider) && has(self.initProvider.odaPrivateEndpointId))",message="spec.forProvider.odaPrivateEndpointId is a required parameter"
	Spec   PrivateEndpointAttachmentSpec   `json:"spec"`
	Status PrivateEndpointAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PrivateEndpointAttachmentList contains a list of PrivateEndpointAttachments
type PrivateEndpointAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PrivateEndpointAttachment `json:"items"`
}

// Repository type metadata.
var (
	PrivateEndpointAttachment_Kind             = "PrivateEndpointAttachment"
	PrivateEndpointAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PrivateEndpointAttachment_Kind}.String()
	PrivateEndpointAttachment_KindAPIVersion   = PrivateEndpointAttachment_Kind + "." + CRDGroupVersion.String()
	PrivateEndpointAttachment_GroupVersionKind = CRDGroupVersion.WithKind(PrivateEndpointAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&PrivateEndpointAttachment{}, &PrivateEndpointAttachmentList{})
}
