/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AutonomousVmClusterSslCertificateManagementInitParameters struct {

	// The autonomous VM cluster OCID.
	AutonomousVMClusterID *string `json:"autonomousVmClusterId,omitempty" tf:"autonomous_vm_cluster_id,omitempty"`

	// The OCID of the certificate bundle.
	CABundleID *string `json:"caBundleId,omitempty" tf:"ca_bundle_id,omitempty"`

	// The OCID of the certificate authority.
	CertificateAuthorityID *string `json:"certificateAuthorityId,omitempty" tf:"certificate_authority_id,omitempty"`

	// Specify SYSTEM for using Oracle managed certificates. Specify BYOC when you want to bring your own certificate.
	CertificateGenerationType *string `json:"certificateGenerationType,omitempty" tf:"certificate_generation_type,omitempty"`

	// The OCID of the certificate to use.
	CertificateID *string `json:"certificateId,omitempty" tf:"certificate_id,omitempty"`
}

type AutonomousVmClusterSslCertificateManagementObservation struct {

	// The autonomous VM cluster OCID.
	AutonomousVMClusterID *string `json:"autonomousVmClusterId,omitempty" tf:"autonomous_vm_cluster_id,omitempty"`

	// The OCID of the certificate bundle.
	CABundleID *string `json:"caBundleId,omitempty" tf:"ca_bundle_id,omitempty"`

	// The OCID of the certificate authority.
	CertificateAuthorityID *string `json:"certificateAuthorityId,omitempty" tf:"certificate_authority_id,omitempty"`

	// Specify SYSTEM for using Oracle managed certificates. Specify BYOC when you want to bring your own certificate.
	CertificateGenerationType *string `json:"certificateGenerationType,omitempty" tf:"certificate_generation_type,omitempty"`

	// The OCID of the certificate to use.
	CertificateID *string `json:"certificateId,omitempty" tf:"certificate_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AutonomousVmClusterSslCertificateManagementParameters struct {

	// The autonomous VM cluster OCID.
	// +kubebuilder:validation:Optional
	AutonomousVMClusterID *string `json:"autonomousVmClusterId,omitempty" tf:"autonomous_vm_cluster_id,omitempty"`

	// The OCID of the certificate bundle.
	// +kubebuilder:validation:Optional
	CABundleID *string `json:"caBundleId,omitempty" tf:"ca_bundle_id,omitempty"`

	// The OCID of the certificate authority.
	// +kubebuilder:validation:Optional
	CertificateAuthorityID *string `json:"certificateAuthorityId,omitempty" tf:"certificate_authority_id,omitempty"`

	// Specify SYSTEM for using Oracle managed certificates. Specify BYOC when you want to bring your own certificate.
	// +kubebuilder:validation:Optional
	CertificateGenerationType *string `json:"certificateGenerationType,omitempty" tf:"certificate_generation_type,omitempty"`

	// The OCID of the certificate to use.
	// +kubebuilder:validation:Optional
	CertificateID *string `json:"certificateId,omitempty" tf:"certificate_id,omitempty"`
}

// AutonomousVmClusterSslCertificateManagementSpec defines the desired state of AutonomousVmClusterSslCertificateManagement
type AutonomousVmClusterSslCertificateManagementSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AutonomousVmClusterSslCertificateManagementParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AutonomousVmClusterSslCertificateManagementInitParameters `json:"initProvider,omitempty"`
}

// AutonomousVmClusterSslCertificateManagementStatus defines the observed state of AutonomousVmClusterSslCertificateManagement.
type AutonomousVmClusterSslCertificateManagementStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AutonomousVmClusterSslCertificateManagementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AutonomousVmClusterSslCertificateManagement is the Schema for the AutonomousVmClusterSslCertificateManagements API. Provides the Autonomous Vm Cluster Ssl Certificate Management resource in Oracle Cloud Infrastructure Database service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type AutonomousVmClusterSslCertificateManagement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.autonomousVmClusterId) || (has(self.initProvider) && has(self.initProvider.autonomousVmClusterId))",message="spec.forProvider.autonomousVmClusterId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.certificateGenerationType) || (has(self.initProvider) && has(self.initProvider.certificateGenerationType))",message="spec.forProvider.certificateGenerationType is a required parameter"
	Spec   AutonomousVmClusterSslCertificateManagementSpec   `json:"spec"`
	Status AutonomousVmClusterSslCertificateManagementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AutonomousVmClusterSslCertificateManagementList contains a list of AutonomousVmClusterSslCertificateManagements
type AutonomousVmClusterSslCertificateManagementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AutonomousVmClusterSslCertificateManagement `json:"items"`
}

// Repository type metadata.
var (
	AutonomousVmClusterSslCertificateManagement_Kind             = "AutonomousVmClusterSslCertificateManagement"
	AutonomousVmClusterSslCertificateManagement_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AutonomousVmClusterSslCertificateManagement_Kind}.String()
	AutonomousVmClusterSslCertificateManagement_KindAPIVersion   = AutonomousVmClusterSslCertificateManagement_Kind + "." + CRDGroupVersion.String()
	AutonomousVmClusterSslCertificateManagement_GroupVersionKind = CRDGroupVersion.WithKind(AutonomousVmClusterSslCertificateManagement_Kind)
)

func init() {
	SchemeBuilder.Register(&AutonomousVmClusterSslCertificateManagement{}, &AutonomousVmClusterSslCertificateManagementList{})
}
