apiVersion: distributeddatabase.oci.upbound.io/v1alpha1
kind: DistributedAutonomousDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: distributeddatabase/v1alpha1/distributedautonomousdatabase
  labels:
    testing.upbound.io/example-name: test_distributed_autonomous_database
  name: test-distributed-autonomous-database
spec:
  forProvider:
    catalogDetails:
    - adminPasswordSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      cloudAutonomousVmClusterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_cloud_autonomous_vm_cluster
      computeCount: ${var.distributed_autonomous_database_catalog_details_compute_count}
      dataStorageSizeInGbs: ${var.distributed_autonomous_database_catalog_details_data_storage_size_in_gbs}
      isAutoScalingEnabled: ${var.distributed_autonomous_database_catalog_details_is_auto_scaling_enabled}
      source: ${var.distributed_autonomous_database_catalog_details_source}
    characterSet: ${var.distributed_autonomous_database_character_set}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    databaseVersion: ${var.distributed_autonomous_database_database_version}
    dbDeploymentType: ${var.distributed_autonomous_database_db_deployment_type}
    dbWorkload: ${var.distributed_autonomous_database_db_workload}
    displayName: ${var.distributed_autonomous_database_display_name}
    listenerPort: ${var.distributed_autonomous_database_listener_port}
    ncharacterSet: ${var.distributed_autonomous_database_ncharacter_set}
    onsPortLocal: ${var.distributed_autonomous_database_ons_port_local}
    onsPortRemote: ${var.distributed_autonomous_database_ons_port_remote}
    prefix: ${var.distributed_autonomous_database_prefix}
    privateEndpointIds: ${var.distributed_autonomous_database_private_endpoint_ids}
    shardDetails:
    - cloudAutonomousVmClusterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_cloud_autonomous_vm_cluster
      computeCount: ${var.distributed_autonomous_database_shard_details_compute_count}
      dataStorageSizeInGbs: ${var.distributed_autonomous_database_shard_details_data_storage_size_in_gbs}
      isAutoScalingEnabled: ${var.distributed_autonomous_database_shard_details_is_auto_scaling_enabled}
      source: ${var.distributed_autonomous_database_shard_details_source}
    shardingMethod: ${var.distributed_autonomous_database_sharding_method}
