/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AiAgent) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AiAgentEndpoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AiAgentKnowledgeBase) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AiAgentTool) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AiDedicatedAiCluster) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AiEndpoint) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AiModel) Hub() {}
