/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type BridgeAgentDependencyInitParameters struct {

	// (Updatable) Object storage bucket where the dependency is uploaded.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Updatable) Compartment identifier.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) The defined tags associated with this resource, if any. Each key is predefined and scoped to namespaces. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Name of the dependency type. This should match the whitelisted enum of dependency names.
	DependencyName *string `json:"dependencyName,omitempty" tf:"dependency_name,omitempty"`

	// (Updatable) Version of the Agent dependency.
	DependencyVersion *string `json:"dependencyVersion,omitempty" tf:"dependency_version,omitempty"`

	// (Updatable) Description about the Agent dependency.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Display name of the Agent dependency.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) The freeform tags associated with this resource, if any. Each tag is a simple key-value pair with no predefined name, type, or namespace/scope. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Object storage namespace associated with the customer's tenancy.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Updatable) Name of the dependency object uploaded by the customer.
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// (Updatable) The system tags associated with this resource, if any. The system tags are set by Oracle cloud infrastructure services. Each key is predefined and scoped to namespaces. For more information, see Resource Tags. Example: {orcl-cloud: {free-tier-retain: true}}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`
}

type BridgeAgentDependencyObservation struct {

	// (Updatable) Object storage bucket where the dependency is uploaded.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// The checksum associated with the dependency object returned by Object Storage.
	Checksum *string `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// (Updatable) Compartment identifier.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) The defined tags associated with this resource, if any. Each key is predefined and scoped to namespaces. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Name of the dependency type. This should match the whitelisted enum of dependency names.
	DependencyName *string `json:"dependencyName,omitempty" tf:"dependency_name,omitempty"`

	// (Updatable) Version of the Agent dependency.
	DependencyVersion *string `json:"dependencyVersion,omitempty" tf:"dependency_version,omitempty"`

	// (Updatable) Description about the Agent dependency.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Display name of the Agent dependency.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The eTag associated with the dependency object returned by Object Storage.
	ETag *string `json:"eTag,omitempty" tf:"e_tag,omitempty"`

	// (Updatable) The freeform tags associated with this resource, if any. Each tag is a simple key-value pair with no predefined name, type, or namespace/scope. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// Unique identifier that is immutable on creation.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A message describing the current state in more detail. For example, it can be used to provide actionable information for a resource in Failed state.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// (Updatable) Object storage namespace associated with the customer's tenancy.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Updatable) Name of the dependency object uploaded by the customer.
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// The current state of AgentDependency.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// (Updatable) The system tags associated with this resource, if any. The system tags are set by Oracle cloud infrastructure services. Each key is predefined and scoped to namespaces. For more information, see Resource Tags. Example: {orcl-cloud: {free-tier-retain: true}}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The time when the AgentDependency was created. An RFC3339 formatted datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`
}

type BridgeAgentDependencyParameters struct {

	// (Updatable) Object storage bucket where the dependency is uploaded.
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Updatable) Compartment identifier.
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) The defined tags associated with this resource, if any. Each key is predefined and scoped to namespaces. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Name of the dependency type. This should match the whitelisted enum of dependency names.
	// +kubebuilder:validation:Optional
	DependencyName *string `json:"dependencyName,omitempty" tf:"dependency_name,omitempty"`

	// (Updatable) Version of the Agent dependency.
	// +kubebuilder:validation:Optional
	DependencyVersion *string `json:"dependencyVersion,omitempty" tf:"dependency_version,omitempty"`

	// (Updatable) Description about the Agent dependency.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) Display name of the Agent dependency.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) The freeform tags associated with this resource, if any. Each tag is a simple key-value pair with no predefined name, type, or namespace/scope. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) Object storage namespace associated with the customer's tenancy.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// (Updatable) Name of the dependency object uploaded by the customer.
	// +kubebuilder:validation:Optional
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// (Updatable) The system tags associated with this resource, if any. The system tags are set by Oracle cloud infrastructure services. Each key is predefined and scoped to namespaces. For more information, see Resource Tags. Example: {orcl-cloud: {free-tier-retain: true}}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`
}

// BridgeAgentDependencySpec defines the desired state of BridgeAgentDependency
type BridgeAgentDependencySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     BridgeAgentDependencyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BridgeAgentDependencyInitParameters `json:"initProvider,omitempty"`
}

// BridgeAgentDependencyStatus defines the observed state of BridgeAgentDependency.
type BridgeAgentDependencyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BridgeAgentDependencyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BridgeAgentDependency is the Schema for the BridgeAgentDependencys API. Provides the Agent Dependency resource in Oracle Cloud Infrastructure Cloud Bridge service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type BridgeAgentDependency struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bucket) || (has(self.initProvider) && has(self.initProvider.bucket))",message="spec.forProvider.bucket is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.compartmentId) || (has(self.initProvider) && has(self.initProvider.compartmentId))",message="spec.forProvider.compartmentId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dependencyName) || (has(self.initProvider) && has(self.initProvider.dependencyName))",message="spec.forProvider.dependencyName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.__namespace__) || (has(self.initProvider) && has(self.initProvider.__namespace__))",message="spec.forProvider.namespace is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.object) || (has(self.initProvider) && has(self.initProvider.object))",message="spec.forProvider.object is a required parameter"
	Spec   BridgeAgentDependencySpec   `json:"spec"`
	Status BridgeAgentDependencyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BridgeAgentDependencyList contains a list of BridgeAgentDependencys
type BridgeAgentDependencyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BridgeAgentDependency `json:"items"`
}

// Repository type metadata.
var (
	BridgeAgentDependency_Kind             = "BridgeAgentDependency"
	BridgeAgentDependency_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BridgeAgentDependency_Kind}.String()
	BridgeAgentDependency_KindAPIVersion   = BridgeAgentDependency_Kind + "." + CRDGroupVersion.String()
	BridgeAgentDependency_GroupVersionKind = CRDGroupVersion.WithKind(BridgeAgentDependency_Kind)
)

func init() {
	SchemeBuilder.Register(&BridgeAgentDependency{}, &BridgeAgentDependencyList{})
}
