/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ChecksPingProbeInitParameters struct {

	// The OCID of the compartment.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// The port on which to probe endpoints. If unspecified, probes will use the default port of their protocol.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// The protocols for ping probes.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// A list of targets (hostnames or IP addresses) of the probe.
	Targets []*string `json:"targets,omitempty" tf:"targets,omitempty"`

	// The probe timeout in seconds. Valid values: 10, 20, 30, and 60. The probe timeout must be less than or equal to intervalInSeconds for monitors.
	TimeoutInSeconds *float64 `json:"timeoutInSeconds,omitempty" tf:"timeout_in_seconds,omitempty"`

	// A list of names of vantage points from which to execute the probe.
	VantagePointNames []*string `json:"vantagePointNames,omitempty" tf:"vantage_point_names,omitempty"`
}

type ChecksPingProbeObservation struct {

	// The OCID of the compartment.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// The region where updates must be made and where results must be fetched from.
	HomeRegion *string `json:"homeRegion,omitempty" tf:"home_region,omitempty"`

	// The OCID of the resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The port on which to probe endpoints. If unspecified, probes will use the default port of their protocol.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// The protocols for ping probes.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// A URL for fetching the probe results.
	ResultsURL *string `json:"resultsUrl,omitempty" tf:"results_url,omitempty"`

	// A list of targets (hostnames or IP addresses) of the probe.
	Targets []*string `json:"targets,omitempty" tf:"targets,omitempty"`

	// The RFC 3339-formatted creation date and time of the probe.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The probe timeout in seconds. Valid values: 10, 20, 30, and 60. The probe timeout must be less than or equal to intervalInSeconds for monitors.
	TimeoutInSeconds *float64 `json:"timeoutInSeconds,omitempty" tf:"timeout_in_seconds,omitempty"`

	// A list of names of vantage points from which to execute the probe.
	VantagePointNames []*string `json:"vantagePointNames,omitempty" tf:"vantage_point_names,omitempty"`
}

type ChecksPingProbeParameters struct {

	// The OCID of the compartment.
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// The port on which to probe endpoints. If unspecified, probes will use the default port of their protocol.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// The protocols for ping probes.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// A list of targets (hostnames or IP addresses) of the probe.
	// +kubebuilder:validation:Optional
	Targets []*string `json:"targets,omitempty" tf:"targets,omitempty"`

	// The probe timeout in seconds. Valid values: 10, 20, 30, and 60. The probe timeout must be less than or equal to intervalInSeconds for monitors.
	// +kubebuilder:validation:Optional
	TimeoutInSeconds *float64 `json:"timeoutInSeconds,omitempty" tf:"timeout_in_seconds,omitempty"`

	// A list of names of vantage points from which to execute the probe.
	// +kubebuilder:validation:Optional
	VantagePointNames []*string `json:"vantagePointNames,omitempty" tf:"vantage_point_names,omitempty"`
}

// ChecksPingProbeSpec defines the desired state of ChecksPingProbe
type ChecksPingProbeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ChecksPingProbeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ChecksPingProbeInitParameters `json:"initProvider,omitempty"`
}

// ChecksPingProbeStatus defines the observed state of ChecksPingProbe.
type ChecksPingProbeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ChecksPingProbeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ChecksPingProbe is the Schema for the ChecksPingProbes API. Provides the Ping Probe resource in Oracle Cloud Infrastructure Health Checks service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type ChecksPingProbe struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.compartmentId) || (has(self.initProvider) && has(self.initProvider.compartmentId))",message="spec.forProvider.compartmentId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.protocol) || (has(self.initProvider) && has(self.initProvider.protocol))",message="spec.forProvider.protocol is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targets) || (has(self.initProvider) && has(self.initProvider.targets))",message="spec.forProvider.targets is a required parameter"
	Spec   ChecksPingProbeSpec   `json:"spec"`
	Status ChecksPingProbeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ChecksPingProbeList contains a list of ChecksPingProbes
type ChecksPingProbeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ChecksPingProbe `json:"items"`
}

// Repository type metadata.
var (
	ChecksPingProbe_Kind             = "ChecksPingProbe"
	ChecksPingProbe_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ChecksPingProbe_Kind}.String()
	ChecksPingProbe_KindAPIVersion   = ChecksPingProbe_Kind + "." + CRDGroupVersion.String()
	ChecksPingProbe_GroupVersionKind = CRDGroupVersion.WithKind(ChecksPingProbe_Kind)
)

func init() {
	SchemeBuilder.Register(&ChecksPingProbe{}, &ChecksPingProbeList{})
}
