/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type AnalyticsNamespaceStorageArchivalConfigInitParameters struct {

	// (Updatable) This is the configuration for data archiving in object storage
	ArchivingConfiguration []ArchivingConfigurationInitParameters `json:"archivingConfiguration,omitempty" tf:"archiving_configuration,omitempty"`

	// The Logging Analytics namespace used for the request.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type AnalyticsNamespaceStorageArchivalConfigObservation struct {

	// (Updatable) This is the configuration for data archiving in object storage
	ArchivingConfiguration []ArchivingConfigurationObservation `json:"archivingConfiguration,omitempty" tf:"archiving_configuration,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// This indicates if old data can be archived for a tenancy
	IsArchivingEnabled *bool `json:"isArchivingEnabled,omitempty" tf:"is_archiving_enabled,omitempty"`

	// The Logging Analytics namespace used for the request.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type AnalyticsNamespaceStorageArchivalConfigParameters struct {

	// (Updatable) This is the configuration for data archiving in object storage
	// +kubebuilder:validation:Optional
	ArchivingConfiguration []ArchivingConfigurationParameters `json:"archivingConfiguration,omitempty" tf:"archiving_configuration,omitempty"`

	// The Logging Analytics namespace used for the request.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type ArchivingConfigurationInitParameters struct {

	// (Updatable) This is the duration data in active storage before data is archived, as described in https://en.wikipedia.org/wiki/ISO_8601#Durations. The largest supported unit is D, e.g. P365D (not P1Y) or P14D (not P2W).
	ActiveStorageDuration *string `json:"activeStorageDuration,omitempty" tf:"active_storage_duration,omitempty"`

	// (Updatable) This is the duration before archived data is deleted from object storage, as described in https://en.wikipedia.org/wiki/ISO_8601#Durations The largest supported unit is D, e.g. P365D (not P1Y) or P14D (not P2W).
	ArchivalStorageDuration *string `json:"archivalStorageDuration,omitempty" tf:"archival_storage_duration,omitempty"`
}

type ArchivingConfigurationObservation struct {

	// (Updatable) This is the duration data in active storage before data is archived, as described in https://en.wikipedia.org/wiki/ISO_8601#Durations. The largest supported unit is D, e.g. P365D (not P1Y) or P14D (not P2W).
	ActiveStorageDuration *string `json:"activeStorageDuration,omitempty" tf:"active_storage_duration,omitempty"`

	// (Updatable) This is the duration before archived data is deleted from object storage, as described in https://en.wikipedia.org/wiki/ISO_8601#Durations The largest supported unit is D, e.g. P365D (not P1Y) or P14D (not P2W).
	ArchivalStorageDuration *string `json:"archivalStorageDuration,omitempty" tf:"archival_storage_duration,omitempty"`
}

type ArchivingConfigurationParameters struct {

	// (Updatable) This is the duration data in active storage before data is archived, as described in https://en.wikipedia.org/wiki/ISO_8601#Durations. The largest supported unit is D, e.g. P365D (not P1Y) or P14D (not P2W).
	// +kubebuilder:validation:Optional
	ActiveStorageDuration *string `json:"activeStorageDuration,omitempty" tf:"active_storage_duration,omitempty"`

	// (Updatable) This is the duration before archived data is deleted from object storage, as described in https://en.wikipedia.org/wiki/ISO_8601#Durations The largest supported unit is D, e.g. P365D (not P1Y) or P14D (not P2W).
	// +kubebuilder:validation:Optional
	ArchivalStorageDuration *string `json:"archivalStorageDuration,omitempty" tf:"archival_storage_duration,omitempty"`
}

// AnalyticsNamespaceStorageArchivalConfigSpec defines the desired state of AnalyticsNamespaceStorageArchivalConfig
type AnalyticsNamespaceStorageArchivalConfigSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AnalyticsNamespaceStorageArchivalConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AnalyticsNamespaceStorageArchivalConfigInitParameters `json:"initProvider,omitempty"`
}

// AnalyticsNamespaceStorageArchivalConfigStatus defines the observed state of AnalyticsNamespaceStorageArchivalConfig.
type AnalyticsNamespaceStorageArchivalConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AnalyticsNamespaceStorageArchivalConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AnalyticsNamespaceStorageArchivalConfig is the Schema for the AnalyticsNamespaceStorageArchivalConfigs API. Provides the Namespace Storage Archival Config resource in Oracle Cloud Infrastructure Log Analytics service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type AnalyticsNamespaceStorageArchivalConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.archivingConfiguration) || (has(self.initProvider) && has(self.initProvider.archivingConfiguration))",message="spec.forProvider.archivingConfiguration is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.__namespace__) || (has(self.initProvider) && has(self.initProvider.__namespace__))",message="spec.forProvider.namespace is a required parameter"
	Spec   AnalyticsNamespaceStorageArchivalConfigSpec   `json:"spec"`
	Status AnalyticsNamespaceStorageArchivalConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AnalyticsNamespaceStorageArchivalConfigList contains a list of AnalyticsNamespaceStorageArchivalConfigs
type AnalyticsNamespaceStorageArchivalConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AnalyticsNamespaceStorageArchivalConfig `json:"items"`
}

// Repository type metadata.
var (
	AnalyticsNamespaceStorageArchivalConfig_Kind             = "AnalyticsNamespaceStorageArchivalConfig"
	AnalyticsNamespaceStorageArchivalConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AnalyticsNamespaceStorageArchivalConfig_Kind}.String()
	AnalyticsNamespaceStorageArchivalConfig_KindAPIVersion   = AnalyticsNamespaceStorageArchivalConfig_Kind + "." + CRDGroupVersion.String()
	AnalyticsNamespaceStorageArchivalConfig_GroupVersionKind = CRDGroupVersion.WithKind(AnalyticsNamespaceStorageArchivalConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&AnalyticsNamespaceStorageArchivalConfig{}, &AnalyticsNamespaceStorageArchivalConfigList{})
}
