// Code generated by provider-oci. DO NOT EDIT.

package scheme

import (
	api1 "github.com/oracle/provider-oci/apis/cluster/batch/v1alpha1"
	api2 "github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1"
	api3 "github.com/oracle/provider-oci/apis/cluster/logging/v1alpha1"
	api4 "github.com/oracle/provider-oci/apis/cluster/networking/v1alpha1"
	api0 "github.com/oracle/provider-oci/apis/cluster/v1beta1"
	api6 "github.com/oracle/provider-oci/apis/namespaced/batch/v1alpha1"
	api7 "github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1"
	api8 "github.com/oracle/provider-oci/apis/namespaced/logging/v1alpha1"
	api9 "github.com/oracle/provider-oci/apis/namespaced/networking/v1alpha1"
	api5 "github.com/oracle/provider-oci/apis/namespaced/v1beta1"
	"k8s.io/apimachinery/pkg/runtime"
)

// AddToSchemes registers only the API types needed by this service runtime.
var AddToSchemes = runtime.SchemeBuilder{
	api0.SchemeBuilder.AddToScheme,
	api1.SchemeBuilder.AddToScheme,
	api2.SchemeBuilder.AddToScheme,
	api3.SchemeBuilder.AddToScheme,
	api4.SchemeBuilder.AddToScheme,
	api5.SchemeBuilder.AddToScheme,
	api6.SchemeBuilder.AddToScheme,
	api7.SchemeBuilder.AddToScheme,
	api8.SchemeBuilder.AddToScheme,
	api9.SchemeBuilder.AddToScheme,
}
