/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type KMSKeyInitParameters struct {

	// (Applicable when environment=HOSTED) (Updatable) The OCID of the KMS encryption key assigned to this Hosted Environment. If the Hosted Environment is using an Oracle-managed Key (i.e., not a CMEK), then the id will be a null string.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The current state of the encryption key assigned to this Hosted Environment. Oracle-managed keys will always report an ACTIVE state.
	KMSKeyState *string `json:"kmsKeyState,omitempty" tf:"kms_key_state,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The OCID of the vault containing the encryption key assigned to this Hosted Environment. If the Hosted Environment is using an Oracle-managed Key (i.e., not a CMEK), then the kmsVaultId will be a null string.
	KMSVaultID *string `json:"kmsVaultId,omitempty" tf:"kms_vault_id,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The timestamp when encryption key was first enabled for this Hosted Environment. RFC3339 formatted.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The timestamp of the last update to the encryption key status. RFC3339 formatted.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type KMSKeyObservation struct {

	// (Applicable when environment=HOSTED) (Updatable) The OCID of the KMS encryption key assigned to this Hosted Environment. If the Hosted Environment is using an Oracle-managed Key (i.e., not a CMEK), then the id will be a null string.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The current state of the encryption key assigned to this Hosted Environment. Oracle-managed keys will always report an ACTIVE state.
	KMSKeyState *string `json:"kmsKeyState,omitempty" tf:"kms_key_state,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The OCID of the vault containing the encryption key assigned to this Hosted Environment. If the Hosted Environment is using an Oracle-managed Key (i.e., not a CMEK), then the kmsVaultId will be a null string.
	KMSVaultID *string `json:"kmsVaultId,omitempty" tf:"kms_vault_id,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The timestamp when encryption key was first enabled for this Hosted Environment. RFC3339 formatted.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The timestamp of the last update to the encryption key status. RFC3339 formatted.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type KMSKeyParameters struct {

	// (Applicable when environment=HOSTED) (Updatable) The OCID of the KMS encryption key assigned to this Hosted Environment. If the Hosted Environment is using an Oracle-managed Key (i.e., not a CMEK), then the id will be a null string.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The current state of the encryption key assigned to this Hosted Environment. Oracle-managed keys will always report an ACTIVE state.
	// +kubebuilder:validation:Optional
	KMSKeyState *string `json:"kmsKeyState,omitempty" tf:"kms_key_state,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The OCID of the vault containing the encryption key assigned to this Hosted Environment. If the Hosted Environment is using an Oracle-managed Key (i.e., not a CMEK), then the kmsVaultId will be a null string.
	// +kubebuilder:validation:Optional
	KMSVaultID *string `json:"kmsVaultId,omitempty" tf:"kms_vault_id,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The timestamp when encryption key was first enabled for this Hosted Environment. RFC3339 formatted.
	// +kubebuilder:validation:Optional
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The timestamp of the last update to the encryption key status. RFC3339 formatted.
	// +kubebuilder:validation:Optional
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type NosqlConfigurationInitParameters struct {

	// (Updatable) The tenancy's OCID
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) The service environment type.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (Updatable) If true, indicates that the request is a dry run. A dry run request does not modify the configuration item details and is used only to perform validation on the submitted data.
	IsOpcDryRun *bool `json:"isOpcDryRun,omitempty" tf:"is_opc_dry_run,omitempty"`

	// (Updatable) Information about the state of the service's encryption key management. The following properties are read-only and ignored when this object is used in UpdateConfiguration: kmsKeyState, timeCreated, timeUpdated.
	KMSKey []KMSKeyInitParameters `json:"kmsKey,omitempty" tf:"kms_key,omitempty"`
}

type NosqlConfigurationObservation struct {

	// (Updatable) The tenancy's OCID
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) The service environment type.
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (Applicable when environment=HOSTED) (Updatable) The OCID of the KMS encryption key assigned to this Hosted Environment. If the Hosted Environment is using an Oracle-managed Key (i.e., not a CMEK), then the id will be a null string.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) If true, indicates that the request is a dry run. A dry run request does not modify the configuration item details and is used only to perform validation on the submitted data.
	IsOpcDryRun *bool `json:"isOpcDryRun,omitempty" tf:"is_opc_dry_run,omitempty"`

	// (Updatable) Information about the state of the service's encryption key management. The following properties are read-only and ignored when this object is used in UpdateConfiguration: kmsKeyState, timeCreated, timeUpdated.
	KMSKey []KMSKeyObservation `json:"kmsKey,omitempty" tf:"kms_key,omitempty"`
}

type NosqlConfigurationParameters struct {

	// (Updatable) The tenancy's OCID
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) The service environment type.
	// +kubebuilder:validation:Optional
	Environment *string `json:"environment,omitempty" tf:"environment,omitempty"`

	// (Updatable) If true, indicates that the request is a dry run. A dry run request does not modify the configuration item details and is used only to perform validation on the submitted data.
	// +kubebuilder:validation:Optional
	IsOpcDryRun *bool `json:"isOpcDryRun,omitempty" tf:"is_opc_dry_run,omitempty"`

	// (Updatable) Information about the state of the service's encryption key management. The following properties are read-only and ignored when this object is used in UpdateConfiguration: kmsKeyState, timeCreated, timeUpdated.
	// +kubebuilder:validation:Optional
	KMSKey []KMSKeyParameters `json:"kmsKey,omitempty" tf:"kms_key,omitempty"`
}

// NosqlConfigurationSpec defines the desired state of NosqlConfiguration
type NosqlConfigurationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NosqlConfigurationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NosqlConfigurationInitParameters `json:"initProvider,omitempty"`
}

// NosqlConfigurationStatus defines the observed state of NosqlConfiguration.
type NosqlConfigurationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NosqlConfigurationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NosqlConfiguration is the Schema for the NosqlConfigurations API. Provides the Configuration resource in Oracle Cloud Infrastructure NoSQL Database service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type NosqlConfiguration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.compartmentId) || (has(self.initProvider) && has(self.initProvider.compartmentId))",message="spec.forProvider.compartmentId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.environment) || (has(self.initProvider) && has(self.initProvider.environment))",message="spec.forProvider.environment is a required parameter"
	Spec   NosqlConfigurationSpec   `json:"spec"`
	Status NosqlConfigurationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NosqlConfigurationList contains a list of NosqlConfigurations
type NosqlConfigurationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NosqlConfiguration `json:"items"`
}

// Repository type metadata.
var (
	NosqlConfiguration_Kind             = "NosqlConfiguration"
	NosqlConfiguration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NosqlConfiguration_Kind}.String()
	NosqlConfiguration_KindAPIVersion   = NosqlConfiguration_Kind + "." + CRDGroupVersion.String()
	NosqlConfiguration_GroupVersionKind = CRDGroupVersion.WithKind(NosqlConfiguration_Kind)
)

func init() {
	SchemeBuilder.Register(&NosqlConfiguration{}, &NosqlConfigurationList{})
}
