//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatastoresInitParameters) DeepCopyInto(out *DatastoresInitParameters) {
	*out = *in
	if in.BlockVolumeIds != nil {
		in, out := &in.BlockVolumeIds, &out.BlockVolumeIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DatastoreType != nil {
		in, out := &in.DatastoreType, &out.DatastoreType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatastoresInitParameters.
func (in *DatastoresInitParameters) DeepCopy() *DatastoresInitParameters {
	if in == nil {
		return nil
	}
	out := new(DatastoresInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatastoresObservation) DeepCopyInto(out *DatastoresObservation) {
	*out = *in
	if in.BlockVolumeIds != nil {
		in, out := &in.BlockVolumeIds, &out.BlockVolumeIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(float64)
		**out = **in
	}
	if in.DatastoreType != nil {
		in, out := &in.DatastoreType, &out.DatastoreType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatastoresObservation.
func (in *DatastoresObservation) DeepCopy() *DatastoresObservation {
	if in == nil {
		return nil
	}
	out := new(DatastoresObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatastoresParameters) DeepCopyInto(out *DatastoresParameters) {
	*out = *in
	if in.BlockVolumeIds != nil {
		in, out := &in.BlockVolumeIds, &out.BlockVolumeIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DatastoreType != nil {
		in, out := &in.DatastoreType, &out.DatastoreType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatastoresParameters.
func (in *DatastoresParameters) DeepCopy() *DatastoresParameters {
	if in == nil {
		return nil
	}
	out := new(DatastoresParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsxiHost) DeepCopyInto(out *EsxiHost) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsxiHost.
func (in *EsxiHost) DeepCopy() *EsxiHost {
	if in == nil {
		return nil
	}
	out := new(EsxiHost)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsxiHost) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsxiHostInitParameters) DeepCopyInto(out *EsxiHostInitParameters) {
	*out = *in
	if in.BillingDonorHostID != nil {
		in, out := &in.BillingDonorHostID, &out.BillingDonorHostID
		*out = new(string)
		**out = **in
	}
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.CurrentSku != nil {
		in, out := &in.CurrentSku, &out.CurrentSku
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiSoftwareVersion != nil {
		in, out := &in.EsxiSoftwareVersion, &out.EsxiSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.FailedEsxiHostID != nil {
		in, out := &in.FailedEsxiHostID, &out.FailedEsxiHostID
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.HostOcpuCount != nil {
		in, out := &in.HostOcpuCount, &out.HostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.HostShapeName != nil {
		in, out := &in.HostShapeName, &out.HostShapeName
		*out = new(string)
		**out = **in
	}
	if in.NextSku != nil {
		in, out := &in.NextSku, &out.NextSku
		*out = new(string)
		**out = **in
	}
	if in.NonUpgradedEsxiHostID != nil {
		in, out := &in.NonUpgradedEsxiHostID, &out.NonUpgradedEsxiHostID
		*out = new(string)
		**out = **in
	}
	if in.SddcID != nil {
		in, out := &in.SddcID, &out.SddcID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsxiHostInitParameters.
func (in *EsxiHostInitParameters) DeepCopy() *EsxiHostInitParameters {
	if in == nil {
		return nil
	}
	out := new(EsxiHostInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsxiHostList) DeepCopyInto(out *EsxiHostList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EsxiHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsxiHostList.
func (in *EsxiHostList) DeepCopy() *EsxiHostList {
	if in == nil {
		return nil
	}
	out := new(EsxiHostList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsxiHostList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsxiHostObservation) DeepCopyInto(out *EsxiHostObservation) {
	*out = *in
	if in.BillingContractEndDate != nil {
		in, out := &in.BillingContractEndDate, &out.BillingContractEndDate
		*out = new(string)
		**out = **in
	}
	if in.BillingDonorHostID != nil {
		in, out := &in.BillingDonorHostID, &out.BillingDonorHostID
		*out = new(string)
		**out = **in
	}
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.ComputeInstanceID != nil {
		in, out := &in.ComputeInstanceID, &out.ComputeInstanceID
		*out = new(string)
		**out = **in
	}
	if in.CurrentCommitment != nil {
		in, out := &in.CurrentCommitment, &out.CurrentCommitment
		*out = new(string)
		**out = **in
	}
	if in.CurrentSku != nil {
		in, out := &in.CurrentSku, &out.CurrentSku
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiSoftwareVersion != nil {
		in, out := &in.EsxiSoftwareVersion, &out.EsxiSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.FailedEsxiHostID != nil {
		in, out := &in.FailedEsxiHostID, &out.FailedEsxiHostID
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.GracePeriodEndDate != nil {
		in, out := &in.GracePeriodEndDate, &out.GracePeriodEndDate
		*out = new(string)
		**out = **in
	}
	if in.HostOcpuCount != nil {
		in, out := &in.HostOcpuCount, &out.HostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.HostShapeName != nil {
		in, out := &in.HostShapeName, &out.HostShapeName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsBillingContinuationInProgress != nil {
		in, out := &in.IsBillingContinuationInProgress, &out.IsBillingContinuationInProgress
		*out = new(bool)
		**out = **in
	}
	if in.IsBillingSwappingInProgress != nil {
		in, out := &in.IsBillingSwappingInProgress, &out.IsBillingSwappingInProgress
		*out = new(bool)
		**out = **in
	}
	if in.NextCommitment != nil {
		in, out := &in.NextCommitment, &out.NextCommitment
		*out = new(string)
		**out = **in
	}
	if in.NextSku != nil {
		in, out := &in.NextSku, &out.NextSku
		*out = new(string)
		**out = **in
	}
	if in.NonUpgradedEsxiHostID != nil {
		in, out := &in.NonUpgradedEsxiHostID, &out.NonUpgradedEsxiHostID
		*out = new(string)
		**out = **in
	}
	if in.ReplacementEsxiHostID != nil {
		in, out := &in.ReplacementEsxiHostID, &out.ReplacementEsxiHostID
		*out = new(string)
		**out = **in
	}
	if in.SddcID != nil {
		in, out := &in.SddcID, &out.SddcID
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.SwapBillingHostID != nil {
		in, out := &in.SwapBillingHostID, &out.SwapBillingHostID
		*out = new(string)
		**out = **in
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeUpdated != nil {
		in, out := &in.TimeUpdated, &out.TimeUpdated
		*out = new(string)
		**out = **in
	}
	if in.UpgradedReplacementEsxiHostID != nil {
		in, out := &in.UpgradedReplacementEsxiHostID, &out.UpgradedReplacementEsxiHostID
		*out = new(string)
		**out = **in
	}
	if in.VmwareSoftwareVersion != nil {
		in, out := &in.VmwareSoftwareVersion, &out.VmwareSoftwareVersion
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsxiHostObservation.
func (in *EsxiHostObservation) DeepCopy() *EsxiHostObservation {
	if in == nil {
		return nil
	}
	out := new(EsxiHostObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsxiHostParameters) DeepCopyInto(out *EsxiHostParameters) {
	*out = *in
	if in.BillingDonorHostID != nil {
		in, out := &in.BillingDonorHostID, &out.BillingDonorHostID
		*out = new(string)
		**out = **in
	}
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.CurrentSku != nil {
		in, out := &in.CurrentSku, &out.CurrentSku
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiSoftwareVersion != nil {
		in, out := &in.EsxiSoftwareVersion, &out.EsxiSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.FailedEsxiHostID != nil {
		in, out := &in.FailedEsxiHostID, &out.FailedEsxiHostID
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.HostOcpuCount != nil {
		in, out := &in.HostOcpuCount, &out.HostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.HostShapeName != nil {
		in, out := &in.HostShapeName, &out.HostShapeName
		*out = new(string)
		**out = **in
	}
	if in.NextSku != nil {
		in, out := &in.NextSku, &out.NextSku
		*out = new(string)
		**out = **in
	}
	if in.NonUpgradedEsxiHostID != nil {
		in, out := &in.NonUpgradedEsxiHostID, &out.NonUpgradedEsxiHostID
		*out = new(string)
		**out = **in
	}
	if in.SddcID != nil {
		in, out := &in.SddcID, &out.SddcID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsxiHostParameters.
func (in *EsxiHostParameters) DeepCopy() *EsxiHostParameters {
	if in == nil {
		return nil
	}
	out := new(EsxiHostParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsxiHostSpec) DeepCopyInto(out *EsxiHostSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsxiHostSpec.
func (in *EsxiHostSpec) DeepCopy() *EsxiHostSpec {
	if in == nil {
		return nil
	}
	out := new(EsxiHostSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsxiHostStatus) DeepCopyInto(out *EsxiHostStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsxiHostStatus.
func (in *EsxiHostStatus) DeepCopy() *EsxiHostStatus {
	if in == nil {
		return nil
	}
	out := new(EsxiHostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HcxOnPremLicensesInitParameters) DeepCopyInto(out *HcxOnPremLicensesInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HcxOnPremLicensesInitParameters.
func (in *HcxOnPremLicensesInitParameters) DeepCopy() *HcxOnPremLicensesInitParameters {
	if in == nil {
		return nil
	}
	out := new(HcxOnPremLicensesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HcxOnPremLicensesObservation) DeepCopyInto(out *HcxOnPremLicensesObservation) {
	*out = *in
	if in.ActivationKey != nil {
		in, out := &in.ActivationKey, &out.ActivationKey
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.SystemName != nil {
		in, out := &in.SystemName, &out.SystemName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HcxOnPremLicensesObservation.
func (in *HcxOnPremLicensesObservation) DeepCopy() *HcxOnPremLicensesObservation {
	if in == nil {
		return nil
	}
	out := new(HcxOnPremLicensesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HcxOnPremLicensesParameters) DeepCopyInto(out *HcxOnPremLicensesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HcxOnPremLicensesParameters.
func (in *HcxOnPremLicensesParameters) DeepCopy() *HcxOnPremLicensesParameters {
	if in == nil {
		return nil
	}
	out := new(HcxOnPremLicensesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialClusterConfigurationsDatastoresInitParameters) DeepCopyInto(out *InitialClusterConfigurationsDatastoresInitParameters) {
	*out = *in
	if in.BlockVolumeIds != nil {
		in, out := &in.BlockVolumeIds, &out.BlockVolumeIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DatastoreType != nil {
		in, out := &in.DatastoreType, &out.DatastoreType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialClusterConfigurationsDatastoresInitParameters.
func (in *InitialClusterConfigurationsDatastoresInitParameters) DeepCopy() *InitialClusterConfigurationsDatastoresInitParameters {
	if in == nil {
		return nil
	}
	out := new(InitialClusterConfigurationsDatastoresInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialClusterConfigurationsDatastoresObservation) DeepCopyInto(out *InitialClusterConfigurationsDatastoresObservation) {
	*out = *in
	if in.BlockVolumeIds != nil {
		in, out := &in.BlockVolumeIds, &out.BlockVolumeIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DatastoreType != nil {
		in, out := &in.DatastoreType, &out.DatastoreType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialClusterConfigurationsDatastoresObservation.
func (in *InitialClusterConfigurationsDatastoresObservation) DeepCopy() *InitialClusterConfigurationsDatastoresObservation {
	if in == nil {
		return nil
	}
	out := new(InitialClusterConfigurationsDatastoresObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialClusterConfigurationsDatastoresParameters) DeepCopyInto(out *InitialClusterConfigurationsDatastoresParameters) {
	*out = *in
	if in.BlockVolumeIds != nil {
		in, out := &in.BlockVolumeIds, &out.BlockVolumeIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DatastoreType != nil {
		in, out := &in.DatastoreType, &out.DatastoreType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialClusterConfigurationsDatastoresParameters.
func (in *InitialClusterConfigurationsDatastoresParameters) DeepCopy() *InitialClusterConfigurationsDatastoresParameters {
	if in == nil {
		return nil
	}
	out := new(InitialClusterConfigurationsDatastoresParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialClusterConfigurationsInitParameters) DeepCopyInto(out *InitialClusterConfigurationsInitParameters) {
	*out = *in
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.Datastores != nil {
		in, out := &in.Datastores, &out.Datastores
		*out = make([]InitialClusterConfigurationsDatastoresInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiHostsCount != nil {
		in, out := &in.EsxiHostsCount, &out.EsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialCommitment != nil {
		in, out := &in.InitialCommitment, &out.InitialCommitment
		*out = new(string)
		**out = **in
	}
	if in.InitialHostOcpuCount != nil {
		in, out := &in.InitialHostOcpuCount, &out.InitialHostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialHostShapeName != nil {
		in, out := &in.InitialHostShapeName, &out.InitialHostShapeName
		*out = new(string)
		**out = **in
	}
	if in.InstanceDisplayNamePrefix != nil {
		in, out := &in.InstanceDisplayNamePrefix, &out.InstanceDisplayNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.IsShieldedInstanceEnabled != nil {
		in, out := &in.IsShieldedInstanceEnabled, &out.IsShieldedInstanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]InitialClusterConfigurationsNetworkConfigurationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VsphereType != nil {
		in, out := &in.VsphereType, &out.VsphereType
		*out = new(string)
		**out = **in
	}
	if in.WorkloadNetworkCidr != nil {
		in, out := &in.WorkloadNetworkCidr, &out.WorkloadNetworkCidr
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialClusterConfigurationsInitParameters.
func (in *InitialClusterConfigurationsInitParameters) DeepCopy() *InitialClusterConfigurationsInitParameters {
	if in == nil {
		return nil
	}
	out := new(InitialClusterConfigurationsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialClusterConfigurationsNetworkConfigurationInitParameters) DeepCopyInto(out *InitialClusterConfigurationsNetworkConfigurationInitParameters) {
	*out = *in
	if in.HcxVlanID != nil {
		in, out := &in.HcxVlanID, &out.HcxVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink1VlanID != nil {
		in, out := &in.NsxEdgeUplink1VlanID, &out.NsxEdgeUplink1VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink2VlanID != nil {
		in, out := &in.NsxEdgeUplink2VlanID, &out.NsxEdgeUplink2VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeVtepVlanID != nil {
		in, out := &in.NsxEdgeVtepVlanID, &out.NsxEdgeVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxVtepVlanID != nil {
		in, out := &in.NsxVtepVlanID, &out.NsxVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningSubnetID != nil {
		in, out := &in.ProvisioningSubnetID, &out.ProvisioningSubnetID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningVlanID != nil {
		in, out := &in.ProvisioningVlanID, &out.ProvisioningVlanID
		*out = new(string)
		**out = **in
	}
	if in.ReplicationVlanID != nil {
		in, out := &in.ReplicationVlanID, &out.ReplicationVlanID
		*out = new(string)
		**out = **in
	}
	if in.VmotionVlanID != nil {
		in, out := &in.VmotionVlanID, &out.VmotionVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsanVlanID != nil {
		in, out := &in.VsanVlanID, &out.VsanVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsphereVlanID != nil {
		in, out := &in.VsphereVlanID, &out.VsphereVlanID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialClusterConfigurationsNetworkConfigurationInitParameters.
func (in *InitialClusterConfigurationsNetworkConfigurationInitParameters) DeepCopy() *InitialClusterConfigurationsNetworkConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(InitialClusterConfigurationsNetworkConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialClusterConfigurationsNetworkConfigurationObservation) DeepCopyInto(out *InitialClusterConfigurationsNetworkConfigurationObservation) {
	*out = *in
	if in.HcxVlanID != nil {
		in, out := &in.HcxVlanID, &out.HcxVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink1VlanID != nil {
		in, out := &in.NsxEdgeUplink1VlanID, &out.NsxEdgeUplink1VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink2VlanID != nil {
		in, out := &in.NsxEdgeUplink2VlanID, &out.NsxEdgeUplink2VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeVtepVlanID != nil {
		in, out := &in.NsxEdgeVtepVlanID, &out.NsxEdgeVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxVtepVlanID != nil {
		in, out := &in.NsxVtepVlanID, &out.NsxVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningSubnetID != nil {
		in, out := &in.ProvisioningSubnetID, &out.ProvisioningSubnetID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningVlanID != nil {
		in, out := &in.ProvisioningVlanID, &out.ProvisioningVlanID
		*out = new(string)
		**out = **in
	}
	if in.ReplicationVlanID != nil {
		in, out := &in.ReplicationVlanID, &out.ReplicationVlanID
		*out = new(string)
		**out = **in
	}
	if in.VmotionVlanID != nil {
		in, out := &in.VmotionVlanID, &out.VmotionVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsanVlanID != nil {
		in, out := &in.VsanVlanID, &out.VsanVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsphereVlanID != nil {
		in, out := &in.VsphereVlanID, &out.VsphereVlanID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialClusterConfigurationsNetworkConfigurationObservation.
func (in *InitialClusterConfigurationsNetworkConfigurationObservation) DeepCopy() *InitialClusterConfigurationsNetworkConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(InitialClusterConfigurationsNetworkConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialClusterConfigurationsNetworkConfigurationParameters) DeepCopyInto(out *InitialClusterConfigurationsNetworkConfigurationParameters) {
	*out = *in
	if in.HcxVlanID != nil {
		in, out := &in.HcxVlanID, &out.HcxVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink1VlanID != nil {
		in, out := &in.NsxEdgeUplink1VlanID, &out.NsxEdgeUplink1VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink2VlanID != nil {
		in, out := &in.NsxEdgeUplink2VlanID, &out.NsxEdgeUplink2VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeVtepVlanID != nil {
		in, out := &in.NsxEdgeVtepVlanID, &out.NsxEdgeVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxVtepVlanID != nil {
		in, out := &in.NsxVtepVlanID, &out.NsxVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningSubnetID != nil {
		in, out := &in.ProvisioningSubnetID, &out.ProvisioningSubnetID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningVlanID != nil {
		in, out := &in.ProvisioningVlanID, &out.ProvisioningVlanID
		*out = new(string)
		**out = **in
	}
	if in.ReplicationVlanID != nil {
		in, out := &in.ReplicationVlanID, &out.ReplicationVlanID
		*out = new(string)
		**out = **in
	}
	if in.VmotionVlanID != nil {
		in, out := &in.VmotionVlanID, &out.VmotionVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsanVlanID != nil {
		in, out := &in.VsanVlanID, &out.VsanVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsphereVlanID != nil {
		in, out := &in.VsphereVlanID, &out.VsphereVlanID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialClusterConfigurationsNetworkConfigurationParameters.
func (in *InitialClusterConfigurationsNetworkConfigurationParameters) DeepCopy() *InitialClusterConfigurationsNetworkConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(InitialClusterConfigurationsNetworkConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialClusterConfigurationsObservation) DeepCopyInto(out *InitialClusterConfigurationsObservation) {
	*out = *in
	if in.ActualEsxiHostsCount != nil {
		in, out := &in.ActualEsxiHostsCount, &out.ActualEsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.Datastores != nil {
		in, out := &in.Datastores, &out.Datastores
		*out = make([]InitialClusterConfigurationsDatastoresObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiHostsCount != nil {
		in, out := &in.EsxiHostsCount, &out.EsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialCommitment != nil {
		in, out := &in.InitialCommitment, &out.InitialCommitment
		*out = new(string)
		**out = **in
	}
	if in.InitialHostOcpuCount != nil {
		in, out := &in.InitialHostOcpuCount, &out.InitialHostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialHostShapeName != nil {
		in, out := &in.InitialHostShapeName, &out.InitialHostShapeName
		*out = new(string)
		**out = **in
	}
	if in.InstanceDisplayNamePrefix != nil {
		in, out := &in.InstanceDisplayNamePrefix, &out.InstanceDisplayNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.IsShieldedInstanceEnabled != nil {
		in, out := &in.IsShieldedInstanceEnabled, &out.IsShieldedInstanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]InitialClusterConfigurationsNetworkConfigurationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VsphereType != nil {
		in, out := &in.VsphereType, &out.VsphereType
		*out = new(string)
		**out = **in
	}
	if in.WorkloadNetworkCidr != nil {
		in, out := &in.WorkloadNetworkCidr, &out.WorkloadNetworkCidr
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialClusterConfigurationsObservation.
func (in *InitialClusterConfigurationsObservation) DeepCopy() *InitialClusterConfigurationsObservation {
	if in == nil {
		return nil
	}
	out := new(InitialClusterConfigurationsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialClusterConfigurationsParameters) DeepCopyInto(out *InitialClusterConfigurationsParameters) {
	*out = *in
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.Datastores != nil {
		in, out := &in.Datastores, &out.Datastores
		*out = make([]InitialClusterConfigurationsDatastoresParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiHostsCount != nil {
		in, out := &in.EsxiHostsCount, &out.EsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialCommitment != nil {
		in, out := &in.InitialCommitment, &out.InitialCommitment
		*out = new(string)
		**out = **in
	}
	if in.InitialHostOcpuCount != nil {
		in, out := &in.InitialHostOcpuCount, &out.InitialHostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialHostShapeName != nil {
		in, out := &in.InitialHostShapeName, &out.InitialHostShapeName
		*out = new(string)
		**out = **in
	}
	if in.InstanceDisplayNamePrefix != nil {
		in, out := &in.InstanceDisplayNamePrefix, &out.InstanceDisplayNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.IsShieldedInstanceEnabled != nil {
		in, out := &in.IsShieldedInstanceEnabled, &out.IsShieldedInstanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]InitialClusterConfigurationsNetworkConfigurationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VsphereType != nil {
		in, out := &in.VsphereType, &out.VsphereType
		*out = new(string)
		**out = **in
	}
	if in.WorkloadNetworkCidr != nil {
		in, out := &in.WorkloadNetworkCidr, &out.WorkloadNetworkCidr
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialClusterConfigurationsParameters.
func (in *InitialClusterConfigurationsParameters) DeepCopy() *InitialClusterConfigurationsParameters {
	if in == nil {
		return nil
	}
	out := new(InitialClusterConfigurationsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialConfigurationInitParameters) DeepCopyInto(out *InitialConfigurationInitParameters) {
	*out = *in
	if in.InitialClusterConfigurations != nil {
		in, out := &in.InitialClusterConfigurations, &out.InitialClusterConfigurations
		*out = make([]InitialClusterConfigurationsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialConfigurationInitParameters.
func (in *InitialConfigurationInitParameters) DeepCopy() *InitialConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(InitialConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialConfigurationObservation) DeepCopyInto(out *InitialConfigurationObservation) {
	*out = *in
	if in.InitialClusterConfigurations != nil {
		in, out := &in.InitialClusterConfigurations, &out.InitialClusterConfigurations
		*out = make([]InitialClusterConfigurationsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialConfigurationObservation.
func (in *InitialConfigurationObservation) DeepCopy() *InitialConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(InitialConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitialConfigurationParameters) DeepCopyInto(out *InitialConfigurationParameters) {
	*out = *in
	if in.InitialClusterConfigurations != nil {
		in, out := &in.InitialClusterConfigurations, &out.InitialClusterConfigurations
		*out = make([]InitialClusterConfigurationsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitialConfigurationParameters.
func (in *InitialConfigurationParameters) DeepCopy() *InitialConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(InitialConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigurationInitParameters) DeepCopyInto(out *NetworkConfigurationInitParameters) {
	*out = *in
	if in.HcxVlanID != nil {
		in, out := &in.HcxVlanID, &out.HcxVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink1VlanID != nil {
		in, out := &in.NsxEdgeUplink1VlanID, &out.NsxEdgeUplink1VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink2VlanID != nil {
		in, out := &in.NsxEdgeUplink2VlanID, &out.NsxEdgeUplink2VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeVtepVlanID != nil {
		in, out := &in.NsxEdgeVtepVlanID, &out.NsxEdgeVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxVtepVlanID != nil {
		in, out := &in.NsxVtepVlanID, &out.NsxVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningSubnetID != nil {
		in, out := &in.ProvisioningSubnetID, &out.ProvisioningSubnetID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningVlanID != nil {
		in, out := &in.ProvisioningVlanID, &out.ProvisioningVlanID
		*out = new(string)
		**out = **in
	}
	if in.ReplicationVlanID != nil {
		in, out := &in.ReplicationVlanID, &out.ReplicationVlanID
		*out = new(string)
		**out = **in
	}
	if in.VmotionVlanID != nil {
		in, out := &in.VmotionVlanID, &out.VmotionVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsanVlanID != nil {
		in, out := &in.VsanVlanID, &out.VsanVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsphereVlanID != nil {
		in, out := &in.VsphereVlanID, &out.VsphereVlanID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigurationInitParameters.
func (in *NetworkConfigurationInitParameters) DeepCopy() *NetworkConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigurationObservation) DeepCopyInto(out *NetworkConfigurationObservation) {
	*out = *in
	if in.HcxVlanID != nil {
		in, out := &in.HcxVlanID, &out.HcxVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink1VlanID != nil {
		in, out := &in.NsxEdgeUplink1VlanID, &out.NsxEdgeUplink1VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink2VlanID != nil {
		in, out := &in.NsxEdgeUplink2VlanID, &out.NsxEdgeUplink2VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeVtepVlanID != nil {
		in, out := &in.NsxEdgeVtepVlanID, &out.NsxEdgeVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxVtepVlanID != nil {
		in, out := &in.NsxVtepVlanID, &out.NsxVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningSubnetID != nil {
		in, out := &in.ProvisioningSubnetID, &out.ProvisioningSubnetID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningVlanID != nil {
		in, out := &in.ProvisioningVlanID, &out.ProvisioningVlanID
		*out = new(string)
		**out = **in
	}
	if in.ReplicationVlanID != nil {
		in, out := &in.ReplicationVlanID, &out.ReplicationVlanID
		*out = new(string)
		**out = **in
	}
	if in.VmotionVlanID != nil {
		in, out := &in.VmotionVlanID, &out.VmotionVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsanVlanID != nil {
		in, out := &in.VsanVlanID, &out.VsanVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsphereVlanID != nil {
		in, out := &in.VsphereVlanID, &out.VsphereVlanID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigurationObservation.
func (in *NetworkConfigurationObservation) DeepCopy() *NetworkConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkConfigurationParameters) DeepCopyInto(out *NetworkConfigurationParameters) {
	*out = *in
	if in.HcxVlanID != nil {
		in, out := &in.HcxVlanID, &out.HcxVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink1VlanID != nil {
		in, out := &in.NsxEdgeUplink1VlanID, &out.NsxEdgeUplink1VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink2VlanID != nil {
		in, out := &in.NsxEdgeUplink2VlanID, &out.NsxEdgeUplink2VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeVtepVlanID != nil {
		in, out := &in.NsxEdgeVtepVlanID, &out.NsxEdgeVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxVtepVlanID != nil {
		in, out := &in.NsxVtepVlanID, &out.NsxVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningSubnetID != nil {
		in, out := &in.ProvisioningSubnetID, &out.ProvisioningSubnetID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningVlanID != nil {
		in, out := &in.ProvisioningVlanID, &out.ProvisioningVlanID
		*out = new(string)
		**out = **in
	}
	if in.ReplicationVlanID != nil {
		in, out := &in.ReplicationVlanID, &out.ReplicationVlanID
		*out = new(string)
		**out = **in
	}
	if in.VmotionVlanID != nil {
		in, out := &in.VmotionVlanID, &out.VmotionVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsanVlanID != nil {
		in, out := &in.VsanVlanID, &out.VsanVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsphereVlanID != nil {
		in, out := &in.VsphereVlanID, &out.VsphereVlanID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkConfigurationParameters.
func (in *NetworkConfigurationParameters) DeepCopy() *NetworkConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(NetworkConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OcvsCluster) DeepCopyInto(out *OcvsCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OcvsCluster.
func (in *OcvsCluster) DeepCopy() *OcvsCluster {
	if in == nil {
		return nil
	}
	out := new(OcvsCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OcvsCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OcvsClusterInitParameters) DeepCopyInto(out *OcvsClusterInitParameters) {
	*out = *in
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.Datastores != nil {
		in, out := &in.Datastores, &out.Datastores
		*out = make([]DatastoresInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiHostsCount != nil {
		in, out := &in.EsxiHostsCount, &out.EsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.EsxiSoftwareVersion != nil {
		in, out := &in.EsxiSoftwareVersion, &out.EsxiSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.InitialCommitment != nil {
		in, out := &in.InitialCommitment, &out.InitialCommitment
		*out = new(string)
		**out = **in
	}
	if in.InitialHostOcpuCount != nil {
		in, out := &in.InitialHostOcpuCount, &out.InitialHostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialHostShapeName != nil {
		in, out := &in.InitialHostShapeName, &out.InitialHostShapeName
		*out = new(string)
		**out = **in
	}
	if in.InstanceDisplayNamePrefix != nil {
		in, out := &in.InstanceDisplayNamePrefix, &out.InstanceDisplayNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.IsShieldedInstanceEnabled != nil {
		in, out := &in.IsShieldedInstanceEnabled, &out.IsShieldedInstanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]NetworkConfigurationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SddcID != nil {
		in, out := &in.SddcID, &out.SddcID
		*out = new(string)
		**out = **in
	}
	if in.VmwareSoftwareVersion != nil {
		in, out := &in.VmwareSoftwareVersion, &out.VmwareSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.WorkloadNetworkCidr != nil {
		in, out := &in.WorkloadNetworkCidr, &out.WorkloadNetworkCidr
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OcvsClusterInitParameters.
func (in *OcvsClusterInitParameters) DeepCopy() *OcvsClusterInitParameters {
	if in == nil {
		return nil
	}
	out := new(OcvsClusterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OcvsClusterList) DeepCopyInto(out *OcvsClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OcvsCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OcvsClusterList.
func (in *OcvsClusterList) DeepCopy() *OcvsClusterList {
	if in == nil {
		return nil
	}
	out := new(OcvsClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OcvsClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OcvsClusterObservation) DeepCopyInto(out *OcvsClusterObservation) {
	*out = *in
	if in.ActualEsxiHostsCount != nil {
		in, out := &in.ActualEsxiHostsCount, &out.ActualEsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.Datastores != nil {
		in, out := &in.Datastores, &out.Datastores
		*out = make([]DatastoresObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiHostsCount != nil {
		in, out := &in.EsxiHostsCount, &out.EsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.EsxiSoftwareVersion != nil {
		in, out := &in.EsxiSoftwareVersion, &out.EsxiSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InitialCommitment != nil {
		in, out := &in.InitialCommitment, &out.InitialCommitment
		*out = new(string)
		**out = **in
	}
	if in.InitialHostOcpuCount != nil {
		in, out := &in.InitialHostOcpuCount, &out.InitialHostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialHostShapeName != nil {
		in, out := &in.InitialHostShapeName, &out.InitialHostShapeName
		*out = new(string)
		**out = **in
	}
	if in.InstanceDisplayNamePrefix != nil {
		in, out := &in.InstanceDisplayNamePrefix, &out.InstanceDisplayNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.IsShieldedInstanceEnabled != nil {
		in, out := &in.IsShieldedInstanceEnabled, &out.IsShieldedInstanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]NetworkConfigurationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SddcID != nil {
		in, out := &in.SddcID, &out.SddcID
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeUpdated != nil {
		in, out := &in.TimeUpdated, &out.TimeUpdated
		*out = new(string)
		**out = **in
	}
	if in.UpgradeLicenses != nil {
		in, out := &in.UpgradeLicenses, &out.UpgradeLicenses
		*out = make([]UpgradeLicensesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VmwareSoftwareVersion != nil {
		in, out := &in.VmwareSoftwareVersion, &out.VmwareSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.VsphereType != nil {
		in, out := &in.VsphereType, &out.VsphereType
		*out = new(string)
		**out = **in
	}
	if in.VsphereUpgradeObjects != nil {
		in, out := &in.VsphereUpgradeObjects, &out.VsphereUpgradeObjects
		*out = make([]VsphereUpgradeObjectsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.WorkloadNetworkCidr != nil {
		in, out := &in.WorkloadNetworkCidr, &out.WorkloadNetworkCidr
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OcvsClusterObservation.
func (in *OcvsClusterObservation) DeepCopy() *OcvsClusterObservation {
	if in == nil {
		return nil
	}
	out := new(OcvsClusterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OcvsClusterParameters) DeepCopyInto(out *OcvsClusterParameters) {
	*out = *in
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.Datastores != nil {
		in, out := &in.Datastores, &out.Datastores
		*out = make([]DatastoresParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiHostsCount != nil {
		in, out := &in.EsxiHostsCount, &out.EsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.EsxiSoftwareVersion != nil {
		in, out := &in.EsxiSoftwareVersion, &out.EsxiSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.InitialCommitment != nil {
		in, out := &in.InitialCommitment, &out.InitialCommitment
		*out = new(string)
		**out = **in
	}
	if in.InitialHostOcpuCount != nil {
		in, out := &in.InitialHostOcpuCount, &out.InitialHostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialHostShapeName != nil {
		in, out := &in.InitialHostShapeName, &out.InitialHostShapeName
		*out = new(string)
		**out = **in
	}
	if in.InstanceDisplayNamePrefix != nil {
		in, out := &in.InstanceDisplayNamePrefix, &out.InstanceDisplayNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.IsShieldedInstanceEnabled != nil {
		in, out := &in.IsShieldedInstanceEnabled, &out.IsShieldedInstanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.NetworkConfiguration != nil {
		in, out := &in.NetworkConfiguration, &out.NetworkConfiguration
		*out = make([]NetworkConfigurationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SddcID != nil {
		in, out := &in.SddcID, &out.SddcID
		*out = new(string)
		**out = **in
	}
	if in.VmwareSoftwareVersion != nil {
		in, out := &in.VmwareSoftwareVersion, &out.VmwareSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.WorkloadNetworkCidr != nil {
		in, out := &in.WorkloadNetworkCidr, &out.WorkloadNetworkCidr
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OcvsClusterParameters.
func (in *OcvsClusterParameters) DeepCopy() *OcvsClusterParameters {
	if in == nil {
		return nil
	}
	out := new(OcvsClusterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OcvsClusterSpec) DeepCopyInto(out *OcvsClusterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OcvsClusterSpec.
func (in *OcvsClusterSpec) DeepCopy() *OcvsClusterSpec {
	if in == nil {
		return nil
	}
	out := new(OcvsClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OcvsClusterStatus) DeepCopyInto(out *OcvsClusterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OcvsClusterStatus.
func (in *OcvsClusterStatus) DeepCopy() *OcvsClusterStatus {
	if in == nil {
		return nil
	}
	out := new(OcvsClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Sddc) DeepCopyInto(out *Sddc) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Sddc.
func (in *Sddc) DeepCopy() *Sddc {
	if in == nil {
		return nil
	}
	out := new(Sddc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Sddc) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcDatastoresInitParameters) DeepCopyInto(out *SddcDatastoresInitParameters) {
	*out = *in
	if in.BlockVolumeIds != nil {
		in, out := &in.BlockVolumeIds, &out.BlockVolumeIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DatastoreType != nil {
		in, out := &in.DatastoreType, &out.DatastoreType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcDatastoresInitParameters.
func (in *SddcDatastoresInitParameters) DeepCopy() *SddcDatastoresInitParameters {
	if in == nil {
		return nil
	}
	out := new(SddcDatastoresInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcDatastoresObservation) DeepCopyInto(out *SddcDatastoresObservation) {
	*out = *in
	if in.BlockVolumeIds != nil {
		in, out := &in.BlockVolumeIds, &out.BlockVolumeIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = new(float64)
		**out = **in
	}
	if in.DatastoreType != nil {
		in, out := &in.DatastoreType, &out.DatastoreType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcDatastoresObservation.
func (in *SddcDatastoresObservation) DeepCopy() *SddcDatastoresObservation {
	if in == nil {
		return nil
	}
	out := new(SddcDatastoresObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcDatastoresParameters) DeepCopyInto(out *SddcDatastoresParameters) {
	*out = *in
	if in.BlockVolumeIds != nil {
		in, out := &in.BlockVolumeIds, &out.BlockVolumeIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DatastoreType != nil {
		in, out := &in.DatastoreType, &out.DatastoreType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcDatastoresParameters.
func (in *SddcDatastoresParameters) DeepCopy() *SddcDatastoresParameters {
	if in == nil {
		return nil
	}
	out := new(SddcDatastoresParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcInitParameters) DeepCopyInto(out *SddcInitParameters) {
	*out = *in
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.Datastores != nil {
		in, out := &in.Datastores, &out.Datastores
		*out = make([]SddcDatastoresInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiHostsCount != nil {
		in, out := &in.EsxiHostsCount, &out.EsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.EsxiSoftwareVersion != nil {
		in, out := &in.EsxiSoftwareVersion, &out.EsxiSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.HcxAction != nil {
		in, out := &in.HcxAction, &out.HcxAction
		*out = new(string)
		**out = **in
	}
	if in.HcxVlanID != nil {
		in, out := &in.HcxVlanID, &out.HcxVlanID
		*out = new(string)
		**out = **in
	}
	if in.InitialConfiguration != nil {
		in, out := &in.InitialConfiguration, &out.InitialConfiguration
		*out = make([]InitialConfigurationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitialHostOcpuCount != nil {
		in, out := &in.InitialHostOcpuCount, &out.InitialHostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialHostShapeName != nil {
		in, out := &in.InitialHostShapeName, &out.InitialHostShapeName
		*out = new(string)
		**out = **in
	}
	if in.InitialSku != nil {
		in, out := &in.InitialSku, &out.InitialSku
		*out = new(string)
		**out = **in
	}
	if in.InstanceDisplayNamePrefix != nil {
		in, out := &in.InstanceDisplayNamePrefix, &out.InstanceDisplayNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.IsHcxEnabled != nil {
		in, out := &in.IsHcxEnabled, &out.IsHcxEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsShieldedInstanceEnabled != nil {
		in, out := &in.IsShieldedInstanceEnabled, &out.IsShieldedInstanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsSingleHostSddc != nil {
		in, out := &in.IsSingleHostSddc, &out.IsSingleHostSddc
		*out = new(bool)
		**out = **in
	}
	if in.NsxEdgeUplink1VlanID != nil {
		in, out := &in.NsxEdgeUplink1VlanID, &out.NsxEdgeUplink1VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink2VlanID != nil {
		in, out := &in.NsxEdgeUplink2VlanID, &out.NsxEdgeUplink2VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeVtepVlanID != nil {
		in, out := &in.NsxEdgeVtepVlanID, &out.NsxEdgeVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxVtepVlanID != nil {
		in, out := &in.NsxVtepVlanID, &out.NsxVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningSubnetID != nil {
		in, out := &in.ProvisioningSubnetID, &out.ProvisioningSubnetID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningVlanID != nil {
		in, out := &in.ProvisioningVlanID, &out.ProvisioningVlanID
		*out = new(string)
		**out = **in
	}
	if in.RefreshHcxLicenseStatus != nil {
		in, out := &in.RefreshHcxLicenseStatus, &out.RefreshHcxLicenseStatus
		*out = new(bool)
		**out = **in
	}
	if in.ReplicationVlanID != nil {
		in, out := &in.ReplicationVlanID, &out.ReplicationVlanID
		*out = new(string)
		**out = **in
	}
	if in.ReservingHcxOnPremiseLicenseKeys != nil {
		in, out := &in.ReservingHcxOnPremiseLicenseKeys, &out.ReservingHcxOnPremiseLicenseKeys
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SSHAuthorizedKeys != nil {
		in, out := &in.SSHAuthorizedKeys, &out.SSHAuthorizedKeys
		*out = new(string)
		**out = **in
	}
	if in.VmotionVlanID != nil {
		in, out := &in.VmotionVlanID, &out.VmotionVlanID
		*out = new(string)
		**out = **in
	}
	if in.VmwareSoftwareVersion != nil {
		in, out := &in.VmwareSoftwareVersion, &out.VmwareSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.VsanVlanID != nil {
		in, out := &in.VsanVlanID, &out.VsanVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsphereVlanID != nil {
		in, out := &in.VsphereVlanID, &out.VsphereVlanID
		*out = new(string)
		**out = **in
	}
	if in.WorkloadNetworkCidr != nil {
		in, out := &in.WorkloadNetworkCidr, &out.WorkloadNetworkCidr
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcInitParameters.
func (in *SddcInitParameters) DeepCopy() *SddcInitParameters {
	if in == nil {
		return nil
	}
	out := new(SddcInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcList) DeepCopyInto(out *SddcList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Sddc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcList.
func (in *SddcList) DeepCopy() *SddcList {
	if in == nil {
		return nil
	}
	out := new(SddcList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SddcList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcObservation) DeepCopyInto(out *SddcObservation) {
	*out = *in
	if in.ActualEsxiHostsCount != nil {
		in, out := &in.ActualEsxiHostsCount, &out.ActualEsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.ClustersCount != nil {
		in, out := &in.ClustersCount, &out.ClustersCount
		*out = new(float64)
		**out = **in
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.Datastores != nil {
		in, out := &in.Datastores, &out.Datastores
		*out = make([]SddcDatastoresObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiHostsCount != nil {
		in, out := &in.EsxiHostsCount, &out.EsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.EsxiSoftwareVersion != nil {
		in, out := &in.EsxiSoftwareVersion, &out.EsxiSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.HcxAction != nil {
		in, out := &in.HcxAction, &out.HcxAction
		*out = new(string)
		**out = **in
	}
	if in.HcxFqdn != nil {
		in, out := &in.HcxFqdn, &out.HcxFqdn
		*out = new(string)
		**out = **in
	}
	if in.HcxInitialPassword != nil {
		in, out := &in.HcxInitialPassword, &out.HcxInitialPassword
		*out = new(string)
		**out = **in
	}
	if in.HcxMode != nil {
		in, out := &in.HcxMode, &out.HcxMode
		*out = new(string)
		**out = **in
	}
	if in.HcxOnPremKey != nil {
		in, out := &in.HcxOnPremKey, &out.HcxOnPremKey
		*out = new(string)
		**out = **in
	}
	if in.HcxOnPremLicenses != nil {
		in, out := &in.HcxOnPremLicenses, &out.HcxOnPremLicenses
		*out = make([]HcxOnPremLicensesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HcxPrivateIPID != nil {
		in, out := &in.HcxPrivateIPID, &out.HcxPrivateIPID
		*out = new(string)
		**out = **in
	}
	if in.HcxVlanID != nil {
		in, out := &in.HcxVlanID, &out.HcxVlanID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InitialConfiguration != nil {
		in, out := &in.InitialConfiguration, &out.InitialConfiguration
		*out = make([]InitialConfigurationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitialHostOcpuCount != nil {
		in, out := &in.InitialHostOcpuCount, &out.InitialHostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialHostShapeName != nil {
		in, out := &in.InitialHostShapeName, &out.InitialHostShapeName
		*out = new(string)
		**out = **in
	}
	if in.InitialSku != nil {
		in, out := &in.InitialSku, &out.InitialSku
		*out = new(string)
		**out = **in
	}
	if in.InstanceDisplayNamePrefix != nil {
		in, out := &in.InstanceDisplayNamePrefix, &out.InstanceDisplayNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.IsHcxEnabled != nil {
		in, out := &in.IsHcxEnabled, &out.IsHcxEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsHcxEnterpriseEnabled != nil {
		in, out := &in.IsHcxEnterpriseEnabled, &out.IsHcxEnterpriseEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsHcxPendingDowngrade != nil {
		in, out := &in.IsHcxPendingDowngrade, &out.IsHcxPendingDowngrade
		*out = new(bool)
		**out = **in
	}
	if in.IsShieldedInstanceEnabled != nil {
		in, out := &in.IsShieldedInstanceEnabled, &out.IsShieldedInstanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsSingleHostSddc != nil {
		in, out := &in.IsSingleHostSddc, &out.IsSingleHostSddc
		*out = new(bool)
		**out = **in
	}
	if in.NsxEdgeUplink1VlanID != nil {
		in, out := &in.NsxEdgeUplink1VlanID, &out.NsxEdgeUplink1VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink2VlanID != nil {
		in, out := &in.NsxEdgeUplink2VlanID, &out.NsxEdgeUplink2VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplinkIPID != nil {
		in, out := &in.NsxEdgeUplinkIPID, &out.NsxEdgeUplinkIPID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeVtepVlanID != nil {
		in, out := &in.NsxEdgeVtepVlanID, &out.NsxEdgeVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxManagerFqdn != nil {
		in, out := &in.NsxManagerFqdn, &out.NsxManagerFqdn
		*out = new(string)
		**out = **in
	}
	if in.NsxManagerInitialPassword != nil {
		in, out := &in.NsxManagerInitialPassword, &out.NsxManagerInitialPassword
		*out = new(string)
		**out = **in
	}
	if in.NsxManagerPrivateIPID != nil {
		in, out := &in.NsxManagerPrivateIPID, &out.NsxManagerPrivateIPID
		*out = new(string)
		**out = **in
	}
	if in.NsxManagerUsername != nil {
		in, out := &in.NsxManagerUsername, &out.NsxManagerUsername
		*out = new(string)
		**out = **in
	}
	if in.NsxOverlaySegmentName != nil {
		in, out := &in.NsxOverlaySegmentName, &out.NsxOverlaySegmentName
		*out = new(string)
		**out = **in
	}
	if in.NsxVtepVlanID != nil {
		in, out := &in.NsxVtepVlanID, &out.NsxVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningSubnetID != nil {
		in, out := &in.ProvisioningSubnetID, &out.ProvisioningSubnetID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningVlanID != nil {
		in, out := &in.ProvisioningVlanID, &out.ProvisioningVlanID
		*out = new(string)
		**out = **in
	}
	if in.RefreshHcxLicenseStatus != nil {
		in, out := &in.RefreshHcxLicenseStatus, &out.RefreshHcxLicenseStatus
		*out = new(bool)
		**out = **in
	}
	if in.ReplicationVlanID != nil {
		in, out := &in.ReplicationVlanID, &out.ReplicationVlanID
		*out = new(string)
		**out = **in
	}
	if in.ReservingHcxOnPremiseLicenseKeys != nil {
		in, out := &in.ReservingHcxOnPremiseLicenseKeys, &out.ReservingHcxOnPremiseLicenseKeys
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SSHAuthorizedKeys != nil {
		in, out := &in.SSHAuthorizedKeys, &out.SSHAuthorizedKeys
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.TimeCreated != nil {
		in, out := &in.TimeCreated, &out.TimeCreated
		*out = new(string)
		**out = **in
	}
	if in.TimeHcxBillingCycleEnd != nil {
		in, out := &in.TimeHcxBillingCycleEnd, &out.TimeHcxBillingCycleEnd
		*out = new(string)
		**out = **in
	}
	if in.TimeHcxLicenseStatusUpdated != nil {
		in, out := &in.TimeHcxLicenseStatusUpdated, &out.TimeHcxLicenseStatusUpdated
		*out = new(string)
		**out = **in
	}
	if in.TimeUpdated != nil {
		in, out := &in.TimeUpdated, &out.TimeUpdated
		*out = new(string)
		**out = **in
	}
	if in.UpgradeLicenses != nil {
		in, out := &in.UpgradeLicenses, &out.UpgradeLicenses
		*out = make([]SddcUpgradeLicensesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VcenterFqdn != nil {
		in, out := &in.VcenterFqdn, &out.VcenterFqdn
		*out = new(string)
		**out = **in
	}
	if in.VcenterInitialPassword != nil {
		in, out := &in.VcenterInitialPassword, &out.VcenterInitialPassword
		*out = new(string)
		**out = **in
	}
	if in.VcenterPrivateIPID != nil {
		in, out := &in.VcenterPrivateIPID, &out.VcenterPrivateIPID
		*out = new(string)
		**out = **in
	}
	if in.VcenterUsername != nil {
		in, out := &in.VcenterUsername, &out.VcenterUsername
		*out = new(string)
		**out = **in
	}
	if in.VmotionVlanID != nil {
		in, out := &in.VmotionVlanID, &out.VmotionVlanID
		*out = new(string)
		**out = **in
	}
	if in.VmwareSoftwareVersion != nil {
		in, out := &in.VmwareSoftwareVersion, &out.VmwareSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.VsanVlanID != nil {
		in, out := &in.VsanVlanID, &out.VsanVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsphereUpgradeGuide != nil {
		in, out := &in.VsphereUpgradeGuide, &out.VsphereUpgradeGuide
		*out = new(string)
		**out = **in
	}
	if in.VsphereUpgradeObjects != nil {
		in, out := &in.VsphereUpgradeObjects, &out.VsphereUpgradeObjects
		*out = make([]SddcVsphereUpgradeObjectsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VsphereVlanID != nil {
		in, out := &in.VsphereVlanID, &out.VsphereVlanID
		*out = new(string)
		**out = **in
	}
	if in.WorkloadNetworkCidr != nil {
		in, out := &in.WorkloadNetworkCidr, &out.WorkloadNetworkCidr
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcObservation.
func (in *SddcObservation) DeepCopy() *SddcObservation {
	if in == nil {
		return nil
	}
	out := new(SddcObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcParameters) DeepCopyInto(out *SddcParameters) {
	*out = *in
	if in.CapacityReservationID != nil {
		in, out := &in.CapacityReservationID, &out.CapacityReservationID
		*out = new(string)
		**out = **in
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ComputeAvailabilityDomain != nil {
		in, out := &in.ComputeAvailabilityDomain, &out.ComputeAvailabilityDomain
		*out = new(string)
		**out = **in
	}
	if in.Datastores != nil {
		in, out := &in.Datastores, &out.Datastores
		*out = make([]SddcDatastoresParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EsxiHostsCount != nil {
		in, out := &in.EsxiHostsCount, &out.EsxiHostsCount
		*out = new(float64)
		**out = **in
	}
	if in.EsxiSoftwareVersion != nil {
		in, out := &in.EsxiSoftwareVersion, &out.EsxiSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.HcxAction != nil {
		in, out := &in.HcxAction, &out.HcxAction
		*out = new(string)
		**out = **in
	}
	if in.HcxVlanID != nil {
		in, out := &in.HcxVlanID, &out.HcxVlanID
		*out = new(string)
		**out = **in
	}
	if in.InitialConfiguration != nil {
		in, out := &in.InitialConfiguration, &out.InitialConfiguration
		*out = make([]InitialConfigurationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitialHostOcpuCount != nil {
		in, out := &in.InitialHostOcpuCount, &out.InitialHostOcpuCount
		*out = new(float64)
		**out = **in
	}
	if in.InitialHostShapeName != nil {
		in, out := &in.InitialHostShapeName, &out.InitialHostShapeName
		*out = new(string)
		**out = **in
	}
	if in.InitialSku != nil {
		in, out := &in.InitialSku, &out.InitialSku
		*out = new(string)
		**out = **in
	}
	if in.InstanceDisplayNamePrefix != nil {
		in, out := &in.InstanceDisplayNamePrefix, &out.InstanceDisplayNamePrefix
		*out = new(string)
		**out = **in
	}
	if in.IsHcxEnabled != nil {
		in, out := &in.IsHcxEnabled, &out.IsHcxEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsShieldedInstanceEnabled != nil {
		in, out := &in.IsShieldedInstanceEnabled, &out.IsShieldedInstanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsSingleHostSddc != nil {
		in, out := &in.IsSingleHostSddc, &out.IsSingleHostSddc
		*out = new(bool)
		**out = **in
	}
	if in.NsxEdgeUplink1VlanID != nil {
		in, out := &in.NsxEdgeUplink1VlanID, &out.NsxEdgeUplink1VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeUplink2VlanID != nil {
		in, out := &in.NsxEdgeUplink2VlanID, &out.NsxEdgeUplink2VlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxEdgeVtepVlanID != nil {
		in, out := &in.NsxEdgeVtepVlanID, &out.NsxEdgeVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.NsxVtepVlanID != nil {
		in, out := &in.NsxVtepVlanID, &out.NsxVtepVlanID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningSubnetID != nil {
		in, out := &in.ProvisioningSubnetID, &out.ProvisioningSubnetID
		*out = new(string)
		**out = **in
	}
	if in.ProvisioningVlanID != nil {
		in, out := &in.ProvisioningVlanID, &out.ProvisioningVlanID
		*out = new(string)
		**out = **in
	}
	if in.RefreshHcxLicenseStatus != nil {
		in, out := &in.RefreshHcxLicenseStatus, &out.RefreshHcxLicenseStatus
		*out = new(bool)
		**out = **in
	}
	if in.ReplicationVlanID != nil {
		in, out := &in.ReplicationVlanID, &out.ReplicationVlanID
		*out = new(string)
		**out = **in
	}
	if in.ReservingHcxOnPremiseLicenseKeys != nil {
		in, out := &in.ReservingHcxOnPremiseLicenseKeys, &out.ReservingHcxOnPremiseLicenseKeys
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SSHAuthorizedKeys != nil {
		in, out := &in.SSHAuthorizedKeys, &out.SSHAuthorizedKeys
		*out = new(string)
		**out = **in
	}
	if in.VmotionVlanID != nil {
		in, out := &in.VmotionVlanID, &out.VmotionVlanID
		*out = new(string)
		**out = **in
	}
	if in.VmwareSoftwareVersion != nil {
		in, out := &in.VmwareSoftwareVersion, &out.VmwareSoftwareVersion
		*out = new(string)
		**out = **in
	}
	if in.VsanVlanID != nil {
		in, out := &in.VsanVlanID, &out.VsanVlanID
		*out = new(string)
		**out = **in
	}
	if in.VsphereVlanID != nil {
		in, out := &in.VsphereVlanID, &out.VsphereVlanID
		*out = new(string)
		**out = **in
	}
	if in.WorkloadNetworkCidr != nil {
		in, out := &in.WorkloadNetworkCidr, &out.WorkloadNetworkCidr
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcParameters.
func (in *SddcParameters) DeepCopy() *SddcParameters {
	if in == nil {
		return nil
	}
	out := new(SddcParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcSpec) DeepCopyInto(out *SddcSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcSpec.
func (in *SddcSpec) DeepCopy() *SddcSpec {
	if in == nil {
		return nil
	}
	out := new(SddcSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcStatus) DeepCopyInto(out *SddcStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcStatus.
func (in *SddcStatus) DeepCopy() *SddcStatus {
	if in == nil {
		return nil
	}
	out := new(SddcStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcUpgradeLicensesInitParameters) DeepCopyInto(out *SddcUpgradeLicensesInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcUpgradeLicensesInitParameters.
func (in *SddcUpgradeLicensesInitParameters) DeepCopy() *SddcUpgradeLicensesInitParameters {
	if in == nil {
		return nil
	}
	out := new(SddcUpgradeLicensesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcUpgradeLicensesObservation) DeepCopyInto(out *SddcUpgradeLicensesObservation) {
	*out = *in
	if in.LicenseKey != nil {
		in, out := &in.LicenseKey, &out.LicenseKey
		*out = new(string)
		**out = **in
	}
	if in.LicenseType != nil {
		in, out := &in.LicenseType, &out.LicenseType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcUpgradeLicensesObservation.
func (in *SddcUpgradeLicensesObservation) DeepCopy() *SddcUpgradeLicensesObservation {
	if in == nil {
		return nil
	}
	out := new(SddcUpgradeLicensesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcUpgradeLicensesParameters) DeepCopyInto(out *SddcUpgradeLicensesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcUpgradeLicensesParameters.
func (in *SddcUpgradeLicensesParameters) DeepCopy() *SddcUpgradeLicensesParameters {
	if in == nil {
		return nil
	}
	out := new(SddcUpgradeLicensesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcVsphereUpgradeObjectsInitParameters) DeepCopyInto(out *SddcVsphereUpgradeObjectsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcVsphereUpgradeObjectsInitParameters.
func (in *SddcVsphereUpgradeObjectsInitParameters) DeepCopy() *SddcVsphereUpgradeObjectsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SddcVsphereUpgradeObjectsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcVsphereUpgradeObjectsObservation) DeepCopyInto(out *SddcVsphereUpgradeObjectsObservation) {
	*out = *in
	if in.DownloadLink != nil {
		in, out := &in.DownloadLink, &out.DownloadLink
		*out = new(string)
		**out = **in
	}
	if in.LinkDescription != nil {
		in, out := &in.LinkDescription, &out.LinkDescription
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcVsphereUpgradeObjectsObservation.
func (in *SddcVsphereUpgradeObjectsObservation) DeepCopy() *SddcVsphereUpgradeObjectsObservation {
	if in == nil {
		return nil
	}
	out := new(SddcVsphereUpgradeObjectsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SddcVsphereUpgradeObjectsParameters) DeepCopyInto(out *SddcVsphereUpgradeObjectsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SddcVsphereUpgradeObjectsParameters.
func (in *SddcVsphereUpgradeObjectsParameters) DeepCopy() *SddcVsphereUpgradeObjectsParameters {
	if in == nil {
		return nil
	}
	out := new(SddcVsphereUpgradeObjectsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeLicensesInitParameters) DeepCopyInto(out *UpgradeLicensesInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeLicensesInitParameters.
func (in *UpgradeLicensesInitParameters) DeepCopy() *UpgradeLicensesInitParameters {
	if in == nil {
		return nil
	}
	out := new(UpgradeLicensesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeLicensesObservation) DeepCopyInto(out *UpgradeLicensesObservation) {
	*out = *in
	if in.LicenseKey != nil {
		in, out := &in.LicenseKey, &out.LicenseKey
		*out = new(string)
		**out = **in
	}
	if in.LicenseType != nil {
		in, out := &in.LicenseType, &out.LicenseType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeLicensesObservation.
func (in *UpgradeLicensesObservation) DeepCopy() *UpgradeLicensesObservation {
	if in == nil {
		return nil
	}
	out := new(UpgradeLicensesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpgradeLicensesParameters) DeepCopyInto(out *UpgradeLicensesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpgradeLicensesParameters.
func (in *UpgradeLicensesParameters) DeepCopy() *UpgradeLicensesParameters {
	if in == nil {
		return nil
	}
	out := new(UpgradeLicensesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VsphereUpgradeObjectsInitParameters) DeepCopyInto(out *VsphereUpgradeObjectsInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VsphereUpgradeObjectsInitParameters.
func (in *VsphereUpgradeObjectsInitParameters) DeepCopy() *VsphereUpgradeObjectsInitParameters {
	if in == nil {
		return nil
	}
	out := new(VsphereUpgradeObjectsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VsphereUpgradeObjectsObservation) DeepCopyInto(out *VsphereUpgradeObjectsObservation) {
	*out = *in
	if in.DownloadLink != nil {
		in, out := &in.DownloadLink, &out.DownloadLink
		*out = new(string)
		**out = **in
	}
	if in.LinkDescription != nil {
		in, out := &in.LinkDescription, &out.LinkDescription
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VsphereUpgradeObjectsObservation.
func (in *VsphereUpgradeObjectsObservation) DeepCopy() *VsphereUpgradeObjectsObservation {
	if in == nil {
		return nil
	}
	out := new(VsphereUpgradeObjectsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VsphereUpgradeObjectsParameters) DeepCopyInto(out *VsphereUpgradeObjectsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VsphereUpgradeObjectsParameters.
func (in *VsphereUpgradeObjectsParameters) DeepCopy() *VsphereUpgradeObjectsParameters {
	if in == nil {
		return nil
	}
	out := new(VsphereUpgradeObjectsParameters)
	in.DeepCopyInto(out)
	return out
}
