/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type OracleDbAzureVaultAssociationInitParameters struct {

	// (Updatable) The OCID of the compartment that contains Oracle DB Azure Vault Association Resource.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Display name of Oracle DB Azure Vault Association.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The OCID of the Oracle DB Azure Connector.
	OracleDBAzureConnectorID *string `json:"oracleDbAzureConnectorId,omitempty" tf:"oracle_db_azure_connector_id,omitempty"`

	// (Updatable) The OCID of the Oracle DB Azure Vault.
	OracleDBAzureVaultID *string `json:"oracleDbAzureVaultId,omitempty" tf:"oracle_db_azure_vault_id,omitempty"`
}

type OracleDbAzureVaultAssociationObservation struct {

	// (Updatable) The OCID of the compartment that contains Oracle DB Azure Vault Association Resource.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Display name of Oracle DB Azure Vault Association.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the Oracle DB Azure Vault Association Resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The Associated Resources are accessible or not.
	IsResourceAccessible *bool `json:"isResourceAccessible,omitempty" tf:"is_resource_accessible,omitempty"`

	// Description of the latest modification of the Oracle DB Azure Vault Association Resource.
	LastModification *string `json:"lastModification,omitempty" tf:"last_modification,omitempty"`

	// Description of the current lifecycle state in more detail.
	LifecycleStateDetails *string `json:"lifecycleStateDetails,omitempty" tf:"lifecycle_state_details,omitempty"`

	// (Updatable) The OCID of the Oracle DB Azure Connector.
	OracleDBAzureConnectorID *string `json:"oracleDbAzureConnectorId,omitempty" tf:"oracle_db_azure_connector_id,omitempty"`

	// (Updatable) The OCID of the Oracle DB Azure Vault.
	OracleDBAzureVaultID *string `json:"oracleDbAzureVaultId,omitempty" tf:"oracle_db_azure_vault_id,omitempty"`

	// The current lifecycle state of the Oracle DB Azure Vault Association Resource.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// Time when the Oracle DB Azure Vault Association was created in RFC 3339 timestamp format, e.g. '2020-05-22T21:10:29.600Z'
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// Time when the Oracle DB Azure Vault Association was last modified, expressed in RFC 3339 timestamp format, e.g. '2020-05-22T21:10:29.600Z'
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type OracleDbAzureVaultAssociationParameters struct {

	// (Updatable) The OCID of the compartment that contains Oracle DB Azure Vault Association Resource.
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Display name of Oracle DB Azure Vault Association.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The OCID of the Oracle DB Azure Connector.
	// +kubebuilder:validation:Optional
	OracleDBAzureConnectorID *string `json:"oracleDbAzureConnectorId,omitempty" tf:"oracle_db_azure_connector_id,omitempty"`

	// (Updatable) The OCID of the Oracle DB Azure Vault.
	// +kubebuilder:validation:Optional
	OracleDBAzureVaultID *string `json:"oracleDbAzureVaultId,omitempty" tf:"oracle_db_azure_vault_id,omitempty"`
}

// OracleDbAzureVaultAssociationSpec defines the desired state of OracleDbAzureVaultAssociation
type OracleDbAzureVaultAssociationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     OracleDbAzureVaultAssociationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OracleDbAzureVaultAssociationInitParameters `json:"initProvider,omitempty"`
}

// OracleDbAzureVaultAssociationStatus defines the observed state of OracleDbAzureVaultAssociation.
type OracleDbAzureVaultAssociationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        OracleDbAzureVaultAssociationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OracleDbAzureVaultAssociation is the Schema for the OracleDbAzureVaultAssociations API. Provides the Oracle Db Azure Vault Association resource in Oracle Cloud Infrastructure Dbmulticloud service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type OracleDbAzureVaultAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.compartmentId) || (has(self.initProvider) && has(self.initProvider.compartmentId))",message="spec.forProvider.compartmentId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.oracleDbAzureConnectorId) || (has(self.initProvider) && has(self.initProvider.oracleDbAzureConnectorId))",message="spec.forProvider.oracleDbAzureConnectorId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.oracleDbAzureVaultId) || (has(self.initProvider) && has(self.initProvider.oracleDbAzureVaultId))",message="spec.forProvider.oracleDbAzureVaultId is a required parameter"
	Spec   OracleDbAzureVaultAssociationSpec   `json:"spec"`
	Status OracleDbAzureVaultAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OracleDbAzureVaultAssociationList contains a list of OracleDbAzureVaultAssociations
type OracleDbAzureVaultAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OracleDbAzureVaultAssociation `json:"items"`
}

// Repository type metadata.
var (
	OracleDbAzureVaultAssociation_Kind             = "OracleDbAzureVaultAssociation"
	OracleDbAzureVaultAssociation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OracleDbAzureVaultAssociation_Kind}.String()
	OracleDbAzureVaultAssociation_KindAPIVersion   = OracleDbAzureVaultAssociation_Kind + "." + CRDGroupVersion.String()
	OracleDbAzureVaultAssociation_GroupVersionKind = CRDGroupVersion.WithKind(OracleDbAzureVaultAssociation_Kind)
)

func init() {
	SchemeBuilder.Register(&OracleDbAzureVaultAssociation{}, &OracleDbAzureVaultAssociationList{})
}
