/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SafeSetUserAssessmentBaselineInitParameters struct {

	// The list of OCIDs for the user assessments that need to be updated while setting the baseline.
	AssessmentIds []*string `json:"assessmentIds,omitempty" tf:"assessment_ids,omitempty"`

	// The OCID of the user assessment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/datalabelingservice/v1alpha1.SafeUserAssessment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	UserAssessmentID *string `json:"userAssessmentId,omitempty" tf:"user_assessment_id,omitempty"`

	// Reference to a SafeUserAssessment in datalabelingservice to populate userAssessmentId.
	// +kubebuilder:validation:Optional
	UserAssessmentIDRef *v1.Reference `json:"userAssessmentIdRef,omitempty" tf:"-"`

	// Selector for a SafeUserAssessment in datalabelingservice to populate userAssessmentId.
	// +kubebuilder:validation:Optional
	UserAssessmentIDSelector *v1.Selector `json:"userAssessmentIdSelector,omitempty" tf:"-"`
}

type SafeSetUserAssessmentBaselineObservation struct {

	// The list of OCIDs for the user assessments that need to be updated while setting the baseline.
	AssessmentIds []*string `json:"assessmentIds,omitempty" tf:"assessment_ids,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the user assessment.
	UserAssessmentID *string `json:"userAssessmentId,omitempty" tf:"user_assessment_id,omitempty"`
}

type SafeSetUserAssessmentBaselineParameters struct {

	// The list of OCIDs for the user assessments that need to be updated while setting the baseline.
	// +kubebuilder:validation:Optional
	AssessmentIds []*string `json:"assessmentIds,omitempty" tf:"assessment_ids,omitempty"`

	// The OCID of the user assessment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/datalabelingservice/v1alpha1.SafeUserAssessment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	UserAssessmentID *string `json:"userAssessmentId,omitempty" tf:"user_assessment_id,omitempty"`

	// Reference to a SafeUserAssessment in datalabelingservice to populate userAssessmentId.
	// +kubebuilder:validation:Optional
	UserAssessmentIDRef *v1.Reference `json:"userAssessmentIdRef,omitempty" tf:"-"`

	// Selector for a SafeUserAssessment in datalabelingservice to populate userAssessmentId.
	// +kubebuilder:validation:Optional
	UserAssessmentIDSelector *v1.Selector `json:"userAssessmentIdSelector,omitempty" tf:"-"`
}

// SafeSetUserAssessmentBaselineSpec defines the desired state of SafeSetUserAssessmentBaseline
type SafeSetUserAssessmentBaselineSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SafeSetUserAssessmentBaselineParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SafeSetUserAssessmentBaselineInitParameters `json:"initProvider,omitempty"`
}

// SafeSetUserAssessmentBaselineStatus defines the observed state of SafeSetUserAssessmentBaseline.
type SafeSetUserAssessmentBaselineStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SafeSetUserAssessmentBaselineObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SafeSetUserAssessmentBaseline is the Schema for the SafeSetUserAssessmentBaselines API. Provides the Set User Assessment Baseline resource in Oracle Cloud Infrastructure Data Safe service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type SafeSetUserAssessmentBaseline struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SafeSetUserAssessmentBaselineSpec   `json:"spec"`
	Status            SafeSetUserAssessmentBaselineStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SafeSetUserAssessmentBaselineList contains a list of SafeSetUserAssessmentBaselines
type SafeSetUserAssessmentBaselineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SafeSetUserAssessmentBaseline `json:"items"`
}

// Repository type metadata.
var (
	SafeSetUserAssessmentBaseline_Kind             = "SafeSetUserAssessmentBaseline"
	SafeSetUserAssessmentBaseline_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SafeSetUserAssessmentBaseline_Kind}.String()
	SafeSetUserAssessmentBaseline_KindAPIVersion   = SafeSetUserAssessmentBaseline_Kind + "." + CRDGroupVersion.String()
	SafeSetUserAssessmentBaseline_GroupVersionKind = CRDGroupVersion.WithKind(SafeSetUserAssessmentBaseline_Kind)
)

func init() {
	SchemeBuilder.Register(&SafeSetUserAssessmentBaseline{}, &SafeSetUserAssessmentBaselineList{})
}
