/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SafeMaskingPoliciesApplyDifferenceToMaskingColumnsInitParameters struct {
	MaskingPolicyID *string `json:"maskingPolicyId,omitempty" tf:"masking_policy_id,omitempty"`

	SdmMaskingPolicyDifferenceID *string `json:"sdmMaskingPolicyDifferenceId,omitempty" tf:"sdm_masking_policy_difference_id,omitempty"`
}

type SafeMaskingPoliciesApplyDifferenceToMaskingColumnsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	MaskingPolicyID *string `json:"maskingPolicyId,omitempty" tf:"masking_policy_id,omitempty"`

	SdmMaskingPolicyDifferenceID *string `json:"sdmMaskingPolicyDifferenceId,omitempty" tf:"sdm_masking_policy_difference_id,omitempty"`
}

type SafeMaskingPoliciesApplyDifferenceToMaskingColumnsParameters struct {

	// +kubebuilder:validation:Optional
	MaskingPolicyID *string `json:"maskingPolicyId,omitempty" tf:"masking_policy_id,omitempty"`

	// +kubebuilder:validation:Optional
	SdmMaskingPolicyDifferenceID *string `json:"sdmMaskingPolicyDifferenceId,omitempty" tf:"sdm_masking_policy_difference_id,omitempty"`
}

// SafeMaskingPoliciesApplyDifferenceToMaskingColumnsSpec defines the desired state of SafeMaskingPoliciesApplyDifferenceToMaskingColumns
type SafeMaskingPoliciesApplyDifferenceToMaskingColumnsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SafeMaskingPoliciesApplyDifferenceToMaskingColumnsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SafeMaskingPoliciesApplyDifferenceToMaskingColumnsInitParameters `json:"initProvider,omitempty"`
}

// SafeMaskingPoliciesApplyDifferenceToMaskingColumnsStatus defines the observed state of SafeMaskingPoliciesApplyDifferenceToMaskingColumns.
type SafeMaskingPoliciesApplyDifferenceToMaskingColumnsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SafeMaskingPoliciesApplyDifferenceToMaskingColumnsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SafeMaskingPoliciesApplyDifferenceToMaskingColumns is the Schema for the SafeMaskingPoliciesApplyDifferenceToMaskingColumnss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type SafeMaskingPoliciesApplyDifferenceToMaskingColumns struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.maskingPolicyId) || (has(self.initProvider) && has(self.initProvider.maskingPolicyId))",message="spec.forProvider.maskingPolicyId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sdmMaskingPolicyDifferenceId) || (has(self.initProvider) && has(self.initProvider.sdmMaskingPolicyDifferenceId))",message="spec.forProvider.sdmMaskingPolicyDifferenceId is a required parameter"
	Spec   SafeMaskingPoliciesApplyDifferenceToMaskingColumnsSpec   `json:"spec"`
	Status SafeMaskingPoliciesApplyDifferenceToMaskingColumnsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SafeMaskingPoliciesApplyDifferenceToMaskingColumnsList contains a list of SafeMaskingPoliciesApplyDifferenceToMaskingColumnss
type SafeMaskingPoliciesApplyDifferenceToMaskingColumnsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SafeMaskingPoliciesApplyDifferenceToMaskingColumns `json:"items"`
}

// Repository type metadata.
var (
	SafeMaskingPoliciesApplyDifferenceToMaskingColumns_Kind             = "SafeMaskingPoliciesApplyDifferenceToMaskingColumns"
	SafeMaskingPoliciesApplyDifferenceToMaskingColumns_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SafeMaskingPoliciesApplyDifferenceToMaskingColumns_Kind}.String()
	SafeMaskingPoliciesApplyDifferenceToMaskingColumns_KindAPIVersion   = SafeMaskingPoliciesApplyDifferenceToMaskingColumns_Kind + "." + CRDGroupVersion.String()
	SafeMaskingPoliciesApplyDifferenceToMaskingColumns_GroupVersionKind = CRDGroupVersion.WithKind(SafeMaskingPoliciesApplyDifferenceToMaskingColumns_Kind)
)

func init() {
	SchemeBuilder.Register(&SafeMaskingPoliciesApplyDifferenceToMaskingColumns{}, &SafeMaskingPoliciesApplyDifferenceToMaskingColumnsList{})
}
