/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type SafeAuditArchiveRetrievalInitParameters struct {

	// (Updatable) The OCID of the compartment that contains the archival retrieval.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Description of the archive retrieval.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The display name of the archive retrieval. The name does not have to be unique, and is changeable.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// End month of the archive retrieval, in the format defined by RFC3339.
	EndDate *string `json:"endDate,omitempty" tf:"end_date,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// Start month of the archive retrieval, in the format defined by RFC3339.
	StartDate *string `json:"startDate,omitempty" tf:"start_date,omitempty"`

	// The OCID of the target associated with the archive retrieval.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cloudguard/v1alpha1.Target
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	TargetID *string `json:"targetId,omitempty" tf:"target_id,omitempty"`

	// Reference to a Target in cloudguard to populate targetId.
	// +kubebuilder:validation:Optional
	TargetIDRef *v1.Reference `json:"targetIdRef,omitempty" tf:"-"`

	// Selector for a Target in cloudguard to populate targetId.
	// +kubebuilder:validation:Optional
	TargetIDSelector *v1.Selector `json:"targetIdSelector,omitempty" tf:"-"`
}

type SafeAuditArchiveRetrievalObservation struct {

	// Total count of audit events to be retrieved from the archive for the specified date range.
	AuditEventCount *string `json:"auditEventCount,omitempty" tf:"audit_event_count,omitempty"`

	// (Updatable) The OCID of the compartment that contains the archival retrieval.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Description of the archive retrieval.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The display name of the archive retrieval. The name does not have to be unique, and is changeable.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// End month of the archive retrieval, in the format defined by RFC3339.
	EndDate *string `json:"endDate,omitempty" tf:"end_date,omitempty"`

	// The Error details of a failed archive retrieval.
	ErrorInfo *string `json:"errorInfo,omitempty" tf:"error_info,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the archive retrieval.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Details about the current state of the archive retrieval.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// Start month of the archive retrieval, in the format defined by RFC3339.
	StartDate *string `json:"startDate,omitempty" tf:"start_date,omitempty"`

	// The current state of the archive retrieval.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The OCID of the target associated with the archive retrieval.
	TargetID *string `json:"targetId,omitempty" tf:"target_id,omitempty"`

	// The date time when archive retrieval request was fulfilled, in the format defined by RFC3339.
	TimeCompleted *string `json:"timeCompleted,omitempty" tf:"time_completed,omitempty"`

	// The date time when retrieved archive data will be deleted from Data Safe and unloaded back into archival.
	TimeOfExpiry *string `json:"timeOfExpiry,omitempty" tf:"time_of_expiry,omitempty"`

	// The date time when archive retrieval was requested, in the format defined by RFC3339.
	TimeRequested *string `json:"timeRequested,omitempty" tf:"time_requested,omitempty"`
}

type SafeAuditArchiveRetrievalParameters struct {

	// (Updatable) The OCID of the compartment that contains the archival retrieval.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Description of the archive retrieval.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) The display name of the archive retrieval. The name does not have to be unique, and is changeable.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// End month of the archive retrieval, in the format defined by RFC3339.
	// +kubebuilder:validation:Optional
	EndDate *string `json:"endDate,omitempty" tf:"end_date,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// Start month of the archive retrieval, in the format defined by RFC3339.
	// +kubebuilder:validation:Optional
	StartDate *string `json:"startDate,omitempty" tf:"start_date,omitempty"`

	// The OCID of the target associated with the archive retrieval.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cloudguard/v1alpha1.Target
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	TargetID *string `json:"targetId,omitempty" tf:"target_id,omitempty"`

	// Reference to a Target in cloudguard to populate targetId.
	// +kubebuilder:validation:Optional
	TargetIDRef *v1.Reference `json:"targetIdRef,omitempty" tf:"-"`

	// Selector for a Target in cloudguard to populate targetId.
	// +kubebuilder:validation:Optional
	TargetIDSelector *v1.Selector `json:"targetIdSelector,omitempty" tf:"-"`
}

// SafeAuditArchiveRetrievalSpec defines the desired state of SafeAuditArchiveRetrieval
type SafeAuditArchiveRetrievalSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SafeAuditArchiveRetrievalParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SafeAuditArchiveRetrievalInitParameters `json:"initProvider,omitempty"`
}

// SafeAuditArchiveRetrievalStatus defines the observed state of SafeAuditArchiveRetrieval.
type SafeAuditArchiveRetrievalStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SafeAuditArchiveRetrievalObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SafeAuditArchiveRetrieval is the Schema for the SafeAuditArchiveRetrievals API. Provides the Audit Archive Retrieval resource in Oracle Cloud Infrastructure Data Safe service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type SafeAuditArchiveRetrieval struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.endDate) || (has(self.initProvider) && has(self.initProvider.endDate))",message="spec.forProvider.endDate is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.startDate) || (has(self.initProvider) && has(self.initProvider.startDate))",message="spec.forProvider.startDate is a required parameter"
	Spec   SafeAuditArchiveRetrievalSpec   `json:"spec"`
	Status SafeAuditArchiveRetrievalStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SafeAuditArchiveRetrievalList contains a list of SafeAuditArchiveRetrievals
type SafeAuditArchiveRetrievalList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SafeAuditArchiveRetrieval `json:"items"`
}

// Repository type metadata.
var (
	SafeAuditArchiveRetrieval_Kind             = "SafeAuditArchiveRetrieval"
	SafeAuditArchiveRetrieval_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SafeAuditArchiveRetrieval_Kind}.String()
	SafeAuditArchiveRetrieval_KindAPIVersion   = SafeAuditArchiveRetrieval_Kind + "." + CRDGroupVersion.String()
	SafeAuditArchiveRetrieval_GroupVersionKind = CRDGroupVersion.WithKind(SafeAuditArchiveRetrieval_Kind)
)

func init() {
	SchemeBuilder.Register(&SafeAuditArchiveRetrieval{}, &SafeAuditArchiveRetrievalList{})
}
