apiVersion: containerengine.oci.m.upbound.io/v1alpha1
kind: Cluster
metadata:
  labels:
    testing.upbound.io/example-name: cluster_label_1
  name: cluster1
  namespace: ${TARGET_NAMESPACE}
spec:
  forProvider:
    type: BASIC_CLUSTER
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    name: cluster1
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn_label_1
    kubernetesVersion: v1.35.2
    clusterPodNetworkOptions:
      - cniType: OCI_VCN_IP_NATIVE
    # Ensure the selected subnet has a route table with internet gateway access
    # and a security list that allows the required traffic.
    endpointConfig:
      - isPublicIpEnabled: true
        subnetIdSelector:
          matchLabels:
            testing.upbound.io/example-name: subnet_label_1
  # providerConfig defaults to "ClusterProviderConfig"; set providerConfigRef to "ProviderConfig" to use namespaced providerConfig.
  providerConfigRef:
    name: default
    kind: ProviderConfig
