//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControl) DeepCopyInto(out *AccessControlOperatorControl) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControl.
func (in *AccessControlOperatorControl) DeepCopy() *AccessControlOperatorControl {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControl)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessControlOperatorControl) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlAssignment) DeepCopyInto(out *AccessControlOperatorControlAssignment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlAssignment.
func (in *AccessControlOperatorControlAssignment) DeepCopy() *AccessControlOperatorControlAssignment {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlAssignment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessControlOperatorControlAssignment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlAssignmentInitParameters) DeepCopyInto(out *AccessControlOperatorControlAssignmentInitParameters) {
	*out = *in
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IsAutoApproveDuringMaintenance != nil {
		in, out := &in.IsAutoApproveDuringMaintenance, &out.IsAutoApproveDuringMaintenance
		*out = new(bool)
		**out = **in
	}
	if in.IsEnforcedAlways != nil {
		in, out := &in.IsEnforcedAlways, &out.IsEnforcedAlways
		*out = new(bool)
		**out = **in
	}
	if in.IsHypervisorLogForwarded != nil {
		in, out := &in.IsHypervisorLogForwarded, &out.IsHypervisorLogForwarded
		*out = new(bool)
		**out = **in
	}
	if in.IsLogForwarded != nil {
		in, out := &in.IsLogForwarded, &out.IsLogForwarded
		*out = new(bool)
		**out = **in
	}
	if in.OperatorControlID != nil {
		in, out := &in.OperatorControlID, &out.OperatorControlID
		*out = new(string)
		**out = **in
	}
	if in.RemoteSyslogServerAddress != nil {
		in, out := &in.RemoteSyslogServerAddress, &out.RemoteSyslogServerAddress
		*out = new(string)
		**out = **in
	}
	if in.RemoteSyslogServerCACert != nil {
		in, out := &in.RemoteSyslogServerCACert, &out.RemoteSyslogServerCACert
		*out = new(string)
		**out = **in
	}
	if in.RemoteSyslogServerPort != nil {
		in, out := &in.RemoteSyslogServerPort, &out.RemoteSyslogServerPort
		*out = new(float64)
		**out = **in
	}
	if in.ResourceCompartmentID != nil {
		in, out := &in.ResourceCompartmentID, &out.ResourceCompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceName != nil {
		in, out := &in.ResourceName, &out.ResourceName
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.TimeAssignmentFrom != nil {
		in, out := &in.TimeAssignmentFrom, &out.TimeAssignmentFrom
		*out = new(string)
		**out = **in
	}
	if in.TimeAssignmentTo != nil {
		in, out := &in.TimeAssignmentTo, &out.TimeAssignmentTo
		*out = new(string)
		**out = **in
	}
	if in.ValidateAssignmentTrigger != nil {
		in, out := &in.ValidateAssignmentTrigger, &out.ValidateAssignmentTrigger
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlAssignmentInitParameters.
func (in *AccessControlOperatorControlAssignmentInitParameters) DeepCopy() *AccessControlOperatorControlAssignmentInitParameters {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlAssignmentInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlAssignmentList) DeepCopyInto(out *AccessControlOperatorControlAssignmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccessControlOperatorControlAssignment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlAssignmentList.
func (in *AccessControlOperatorControlAssignmentList) DeepCopy() *AccessControlOperatorControlAssignmentList {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlAssignmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessControlOperatorControlAssignmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlAssignmentObservation) DeepCopyInto(out *AccessControlOperatorControlAssignmentObservation) {
	*out = *in
	if in.AssignerID != nil {
		in, out := &in.AssignerID, &out.AssignerID
		*out = new(string)
		**out = **in
	}
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.DetachmentDescription != nil {
		in, out := &in.DetachmentDescription, &out.DetachmentDescription
		*out = new(string)
		**out = **in
	}
	if in.ErrorCode != nil {
		in, out := &in.ErrorCode, &out.ErrorCode
		*out = new(float64)
		**out = **in
	}
	if in.ErrorMessage != nil {
		in, out := &in.ErrorMessage, &out.ErrorMessage
		*out = new(string)
		**out = **in
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsAutoApproveDuringMaintenance != nil {
		in, out := &in.IsAutoApproveDuringMaintenance, &out.IsAutoApproveDuringMaintenance
		*out = new(bool)
		**out = **in
	}
	if in.IsDefaultAssignment != nil {
		in, out := &in.IsDefaultAssignment, &out.IsDefaultAssignment
		*out = new(bool)
		**out = **in
	}
	if in.IsEnforcedAlways != nil {
		in, out := &in.IsEnforcedAlways, &out.IsEnforcedAlways
		*out = new(bool)
		**out = **in
	}
	if in.IsHypervisorLogForwarded != nil {
		in, out := &in.IsHypervisorLogForwarded, &out.IsHypervisorLogForwarded
		*out = new(bool)
		**out = **in
	}
	if in.IsLogForwarded != nil {
		in, out := &in.IsLogForwarded, &out.IsLogForwarded
		*out = new(bool)
		**out = **in
	}
	if in.LifecycleDetails != nil {
		in, out := &in.LifecycleDetails, &out.LifecycleDetails
		*out = new(string)
		**out = **in
	}
	if in.OpControlName != nil {
		in, out := &in.OpControlName, &out.OpControlName
		*out = new(string)
		**out = **in
	}
	if in.OperatorControlID != nil {
		in, out := &in.OperatorControlID, &out.OperatorControlID
		*out = new(string)
		**out = **in
	}
	if in.RemoteSyslogServerAddress != nil {
		in, out := &in.RemoteSyslogServerAddress, &out.RemoteSyslogServerAddress
		*out = new(string)
		**out = **in
	}
	if in.RemoteSyslogServerCACert != nil {
		in, out := &in.RemoteSyslogServerCACert, &out.RemoteSyslogServerCACert
		*out = new(string)
		**out = **in
	}
	if in.RemoteSyslogServerPort != nil {
		in, out := &in.RemoteSyslogServerPort, &out.RemoteSyslogServerPort
		*out = new(float64)
		**out = **in
	}
	if in.ResourceCompartmentID != nil {
		in, out := &in.ResourceCompartmentID, &out.ResourceCompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceName != nil {
		in, out := &in.ResourceName, &out.ResourceName
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.TimeAssignmentFrom != nil {
		in, out := &in.TimeAssignmentFrom, &out.TimeAssignmentFrom
		*out = new(string)
		**out = **in
	}
	if in.TimeAssignmentTo != nil {
		in, out := &in.TimeAssignmentTo, &out.TimeAssignmentTo
		*out = new(string)
		**out = **in
	}
	if in.TimeOfAssignment != nil {
		in, out := &in.TimeOfAssignment, &out.TimeOfAssignment
		*out = new(string)
		**out = **in
	}
	if in.TimeOfDeletion != nil {
		in, out := &in.TimeOfDeletion, &out.TimeOfDeletion
		*out = new(string)
		**out = **in
	}
	if in.UnassignerID != nil {
		in, out := &in.UnassignerID, &out.UnassignerID
		*out = new(string)
		**out = **in
	}
	if in.ValidateAssignmentTrigger != nil {
		in, out := &in.ValidateAssignmentTrigger, &out.ValidateAssignmentTrigger
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlAssignmentObservation.
func (in *AccessControlOperatorControlAssignmentObservation) DeepCopy() *AccessControlOperatorControlAssignmentObservation {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlAssignmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlAssignmentParameters) DeepCopyInto(out *AccessControlOperatorControlAssignmentParameters) {
	*out = *in
	if in.Comment != nil {
		in, out := &in.Comment, &out.Comment
		*out = new(string)
		**out = **in
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IsAutoApproveDuringMaintenance != nil {
		in, out := &in.IsAutoApproveDuringMaintenance, &out.IsAutoApproveDuringMaintenance
		*out = new(bool)
		**out = **in
	}
	if in.IsEnforcedAlways != nil {
		in, out := &in.IsEnforcedAlways, &out.IsEnforcedAlways
		*out = new(bool)
		**out = **in
	}
	if in.IsHypervisorLogForwarded != nil {
		in, out := &in.IsHypervisorLogForwarded, &out.IsHypervisorLogForwarded
		*out = new(bool)
		**out = **in
	}
	if in.IsLogForwarded != nil {
		in, out := &in.IsLogForwarded, &out.IsLogForwarded
		*out = new(bool)
		**out = **in
	}
	if in.OperatorControlID != nil {
		in, out := &in.OperatorControlID, &out.OperatorControlID
		*out = new(string)
		**out = **in
	}
	if in.RemoteSyslogServerAddress != nil {
		in, out := &in.RemoteSyslogServerAddress, &out.RemoteSyslogServerAddress
		*out = new(string)
		**out = **in
	}
	if in.RemoteSyslogServerCACert != nil {
		in, out := &in.RemoteSyslogServerCACert, &out.RemoteSyslogServerCACert
		*out = new(string)
		**out = **in
	}
	if in.RemoteSyslogServerPort != nil {
		in, out := &in.RemoteSyslogServerPort, &out.RemoteSyslogServerPort
		*out = new(float64)
		**out = **in
	}
	if in.ResourceCompartmentID != nil {
		in, out := &in.ResourceCompartmentID, &out.ResourceCompartmentID
		*out = new(string)
		**out = **in
	}
	if in.ResourceID != nil {
		in, out := &in.ResourceID, &out.ResourceID
		*out = new(string)
		**out = **in
	}
	if in.ResourceName != nil {
		in, out := &in.ResourceName, &out.ResourceName
		*out = new(string)
		**out = **in
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.TimeAssignmentFrom != nil {
		in, out := &in.TimeAssignmentFrom, &out.TimeAssignmentFrom
		*out = new(string)
		**out = **in
	}
	if in.TimeAssignmentTo != nil {
		in, out := &in.TimeAssignmentTo, &out.TimeAssignmentTo
		*out = new(string)
		**out = **in
	}
	if in.ValidateAssignmentTrigger != nil {
		in, out := &in.ValidateAssignmentTrigger, &out.ValidateAssignmentTrigger
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlAssignmentParameters.
func (in *AccessControlOperatorControlAssignmentParameters) DeepCopy() *AccessControlOperatorControlAssignmentParameters {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlAssignmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlAssignmentSpec) DeepCopyInto(out *AccessControlOperatorControlAssignmentSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlAssignmentSpec.
func (in *AccessControlOperatorControlAssignmentSpec) DeepCopy() *AccessControlOperatorControlAssignmentSpec {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlAssignmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlAssignmentStatus) DeepCopyInto(out *AccessControlOperatorControlAssignmentStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlAssignmentStatus.
func (in *AccessControlOperatorControlAssignmentStatus) DeepCopy() *AccessControlOperatorControlAssignmentStatus {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlAssignmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlInitParameters) DeepCopyInto(out *AccessControlOperatorControlInitParameters) {
	*out = *in
	if in.ApproverGroupsList != nil {
		in, out := &in.ApproverGroupsList, &out.ApproverGroupsList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ApproversList != nil {
		in, out := &in.ApproversList, &out.ApproversList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EmailIDList != nil {
		in, out := &in.EmailIDList, &out.EmailIDList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IsFullyPreApproved != nil {
		in, out := &in.IsFullyPreApproved, &out.IsFullyPreApproved
		*out = new(bool)
		**out = **in
	}
	if in.NumberOfApprovers != nil {
		in, out := &in.NumberOfApprovers, &out.NumberOfApprovers
		*out = new(float64)
		**out = **in
	}
	if in.OperatorControlName != nil {
		in, out := &in.OperatorControlName, &out.OperatorControlName
		*out = new(string)
		**out = **in
	}
	if in.PreApprovedOpActionList != nil {
		in, out := &in.PreApprovedOpActionList, &out.PreApprovedOpActionList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.SystemMessage != nil {
		in, out := &in.SystemMessage, &out.SystemMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlInitParameters.
func (in *AccessControlOperatorControlInitParameters) DeepCopy() *AccessControlOperatorControlInitParameters {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlList) DeepCopyInto(out *AccessControlOperatorControlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AccessControlOperatorControl, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlList.
func (in *AccessControlOperatorControlList) DeepCopy() *AccessControlOperatorControlList {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AccessControlOperatorControlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlObservation) DeepCopyInto(out *AccessControlOperatorControlObservation) {
	*out = *in
	if in.ApprovalRequiredOpActionList != nil {
		in, out := &in.ApprovalRequiredOpActionList, &out.ApprovalRequiredOpActionList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ApproverGroupsList != nil {
		in, out := &in.ApproverGroupsList, &out.ApproverGroupsList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ApproversList != nil {
		in, out := &in.ApproversList, &out.ApproversList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EmailIDList != nil {
		in, out := &in.EmailIDList, &out.EmailIDList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsDefaultOperatorControl != nil {
		in, out := &in.IsDefaultOperatorControl, &out.IsDefaultOperatorControl
		*out = new(bool)
		**out = **in
	}
	if in.IsFullyPreApproved != nil {
		in, out := &in.IsFullyPreApproved, &out.IsFullyPreApproved
		*out = new(bool)
		**out = **in
	}
	if in.LastModifiedInfo != nil {
		in, out := &in.LastModifiedInfo, &out.LastModifiedInfo
		*out = new(string)
		**out = **in
	}
	if in.NumberOfApprovers != nil {
		in, out := &in.NumberOfApprovers, &out.NumberOfApprovers
		*out = new(float64)
		**out = **in
	}
	if in.OperatorControlName != nil {
		in, out := &in.OperatorControlName, &out.OperatorControlName
		*out = new(string)
		**out = **in
	}
	if in.PreApprovedOpActionList != nil {
		in, out := &in.PreApprovedOpActionList, &out.PreApprovedOpActionList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(string)
		**out = **in
	}
	if in.SystemMessage != nil {
		in, out := &in.SystemMessage, &out.SystemMessage
		*out = new(string)
		**out = **in
	}
	if in.TimeOfCreation != nil {
		in, out := &in.TimeOfCreation, &out.TimeOfCreation
		*out = new(string)
		**out = **in
	}
	if in.TimeOfDeletion != nil {
		in, out := &in.TimeOfDeletion, &out.TimeOfDeletion
		*out = new(string)
		**out = **in
	}
	if in.TimeOfModification != nil {
		in, out := &in.TimeOfModification, &out.TimeOfModification
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlObservation.
func (in *AccessControlOperatorControlObservation) DeepCopy() *AccessControlOperatorControlObservation {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlParameters) DeepCopyInto(out *AccessControlOperatorControlParameters) {
	*out = *in
	if in.ApproverGroupsList != nil {
		in, out := &in.ApproverGroupsList, &out.ApproverGroupsList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ApproversList != nil {
		in, out := &in.ApproversList, &out.ApproversList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CompartmentID != nil {
		in, out := &in.CompartmentID, &out.CompartmentID
		*out = new(string)
		**out = **in
	}
	if in.DefinedTags != nil {
		in, out := &in.DefinedTags, &out.DefinedTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EmailIDList != nil {
		in, out := &in.EmailIDList, &out.EmailIDList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FreeformTags != nil {
		in, out := &in.FreeformTags, &out.FreeformTags
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.IsFullyPreApproved != nil {
		in, out := &in.IsFullyPreApproved, &out.IsFullyPreApproved
		*out = new(bool)
		**out = **in
	}
	if in.NumberOfApprovers != nil {
		in, out := &in.NumberOfApprovers, &out.NumberOfApprovers
		*out = new(float64)
		**out = **in
	}
	if in.OperatorControlName != nil {
		in, out := &in.OperatorControlName, &out.OperatorControlName
		*out = new(string)
		**out = **in
	}
	if in.PreApprovedOpActionList != nil {
		in, out := &in.PreApprovedOpActionList, &out.PreApprovedOpActionList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ResourceType != nil {
		in, out := &in.ResourceType, &out.ResourceType
		*out = new(string)
		**out = **in
	}
	if in.SystemMessage != nil {
		in, out := &in.SystemMessage, &out.SystemMessage
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlParameters.
func (in *AccessControlOperatorControlParameters) DeepCopy() *AccessControlOperatorControlParameters {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlSpec) DeepCopyInto(out *AccessControlOperatorControlSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlSpec.
func (in *AccessControlOperatorControlSpec) DeepCopy() *AccessControlOperatorControlSpec {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessControlOperatorControlStatus) DeepCopyInto(out *AccessControlOperatorControlStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessControlOperatorControlStatus.
func (in *AccessControlOperatorControlStatus) DeepCopy() *AccessControlOperatorControlStatus {
	if in == nil {
		return nil
	}
	out := new(AccessControlOperatorControlStatus)
	in.DeepCopyInto(out)
	return out
}
