/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type InstanceMetastoreConfigInitParameters struct {

	// (Updatable) An optional integer, when flipped triggers activation of metastore config.
	ActivateTrigger *float64 `json:"activateTrigger,omitempty" tf:"activate_trigger,omitempty"`

	// (Updatable) The ID of BDS Api Key used for Data Catalog metastore integration.
	BdsAPIKeyID *string `json:"bdsApiKeyId,omitempty" tf:"bds_api_key_id,omitempty"`

	// (Updatable) Base-64 encoded passphrase of the BDS Api Key.
	BdsAPIKeyPassphraseSecretRef v1.SecretKeySelector `json:"bdsApiKeyPassphraseSecretRef" tf:"-"`

	// The OCID of the cluster.
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	// (Updatable) Base-64 encoded password for the cluster admin user.
	ClusterAdminPasswordSecretRef v1.SecretKeySelector `json:"clusterAdminPasswordSecretRef" tf:"-"`

	// (Updatable) The display name of the metastore configuration
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The OCID of the Data Catalog metastore.
	MetastoreID *string `json:"metastoreId,omitempty" tf:"metastore_id,omitempty"`
}

type InstanceMetastoreConfigObservation struct {

	// (Updatable) An optional integer, when flipped triggers activation of metastore config.
	ActivateTrigger *float64 `json:"activateTrigger,omitempty" tf:"activate_trigger,omitempty"`

	// (Updatable) The ID of BDS Api Key used for Data Catalog metastore integration.
	BdsAPIKeyID *string `json:"bdsApiKeyId,omitempty" tf:"bds_api_key_id,omitempty"`

	// The OCID of the cluster.
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	// (Updatable) The display name of the metastore configuration
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The ID of the metastore configuration
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The OCID of the Data Catalog metastore.
	MetastoreID *string `json:"metastoreId,omitempty" tf:"metastore_id,omitempty"`

	// The type of the metastore in the metastore configuration.
	MetastoreType *string `json:"metastoreType,omitempty" tf:"metastore_type,omitempty"`

	// the lifecycle state of the metastore configuration.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The time when the configuration was created, shown as an RFC 3339 formatted datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The time when the configuration was updated, shown as an RFC 3339 formatted datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type InstanceMetastoreConfigParameters struct {

	// (Updatable) An optional integer, when flipped triggers activation of metastore config.
	// +kubebuilder:validation:Optional
	ActivateTrigger *float64 `json:"activateTrigger,omitempty" tf:"activate_trigger,omitempty"`

	// (Updatable) The ID of BDS Api Key used for Data Catalog metastore integration.
	// +kubebuilder:validation:Optional
	BdsAPIKeyID *string `json:"bdsApiKeyId,omitempty" tf:"bds_api_key_id,omitempty"`

	// (Updatable) Base-64 encoded passphrase of the BDS Api Key.
	// +kubebuilder:validation:Optional
	BdsAPIKeyPassphraseSecretRef v1.SecretKeySelector `json:"bdsApiKeyPassphraseSecretRef" tf:"-"`

	// The OCID of the cluster.
	// +kubebuilder:validation:Optional
	BdsInstanceID *string `json:"bdsInstanceId,omitempty" tf:"bds_instance_id,omitempty"`

	// (Updatable) Base-64 encoded password for the cluster admin user.
	// +kubebuilder:validation:Optional
	ClusterAdminPasswordSecretRef v1.SecretKeySelector `json:"clusterAdminPasswordSecretRef" tf:"-"`

	// (Updatable) The display name of the metastore configuration
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The OCID of the Data Catalog metastore.
	// +kubebuilder:validation:Optional
	MetastoreID *string `json:"metastoreId,omitempty" tf:"metastore_id,omitempty"`
}

// InstanceMetastoreConfigSpec defines the desired state of InstanceMetastoreConfig
type InstanceMetastoreConfigSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     InstanceMetastoreConfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceMetastoreConfigInitParameters `json:"initProvider,omitempty"`
}

// InstanceMetastoreConfigStatus defines the observed state of InstanceMetastoreConfig.
type InstanceMetastoreConfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        InstanceMetastoreConfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InstanceMetastoreConfig is the Schema for the InstanceMetastoreConfigs API. Provides the Bds Instance Metastore Config resource in Oracle Cloud Infrastructure Big Data Service service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type InstanceMetastoreConfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bdsApiKeyId) || (has(self.initProvider) && has(self.initProvider.bdsApiKeyId))",message="spec.forProvider.bdsApiKeyId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bdsApiKeyPassphraseSecretRef)",message="spec.forProvider.bdsApiKeyPassphraseSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.bdsInstanceId) || (has(self.initProvider) && has(self.initProvider.bdsInstanceId))",message="spec.forProvider.bdsInstanceId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clusterAdminPasswordSecretRef)",message="spec.forProvider.clusterAdminPasswordSecretRef is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.metastoreId) || (has(self.initProvider) && has(self.initProvider.metastoreId))",message="spec.forProvider.metastoreId is a required parameter"
	Spec   InstanceMetastoreConfigSpec   `json:"spec"`
	Status InstanceMetastoreConfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceMetastoreConfigList contains a list of InstanceMetastoreConfigs
type InstanceMetastoreConfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InstanceMetastoreConfig `json:"items"`
}

// Repository type metadata.
var (
	InstanceMetastoreConfig_Kind             = "InstanceMetastoreConfig"
	InstanceMetastoreConfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InstanceMetastoreConfig_Kind}.String()
	InstanceMetastoreConfig_KindAPIVersion   = InstanceMetastoreConfig_Kind + "." + CRDGroupVersion.String()
	InstanceMetastoreConfig_GroupVersionKind = CRDGroupVersion.WithKind(InstanceMetastoreConfig_Kind)
)

func init() {
	SchemeBuilder.Register(&InstanceMetastoreConfig{}, &InstanceMetastoreConfigList{})
}
