/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type FirewallNetworkFirewallPolicyServiceInitParameters struct {

	// Unique Network Firewall Policy identifier
	NetworkFirewallPolicyID *string `json:"networkFirewallPolicyId,omitempty" tf:"network_firewall_policy_id,omitempty"`

	// (Updatable) List of port-ranges to be used.
	PortRanges []PortRangesInitParameters `json:"portRanges,omitempty" tf:"port_ranges,omitempty"`

	// Describes the type of Service. The accepted values are
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type FirewallNetworkFirewallPolicyServiceObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Unique Network Firewall Policy identifier
	NetworkFirewallPolicyID *string `json:"networkFirewallPolicyId,omitempty" tf:"network_firewall_policy_id,omitempty"`

	// OCID of the Network Firewall Policy this service belongs to.
	ParentResourceID *string `json:"parentResourceId,omitempty" tf:"parent_resource_id,omitempty"`

	// (Updatable) List of port-ranges to be used.
	PortRanges []PortRangesObservation `json:"portRanges,omitempty" tf:"port_ranges,omitempty"`

	// Describes the type of Service. The accepted values are
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type FirewallNetworkFirewallPolicyServiceParameters struct {

	// Unique Network Firewall Policy identifier
	// +kubebuilder:validation:Optional
	NetworkFirewallPolicyID *string `json:"networkFirewallPolicyId,omitempty" tf:"network_firewall_policy_id,omitempty"`

	// (Updatable) List of port-ranges to be used.
	// +kubebuilder:validation:Optional
	PortRanges []PortRangesParameters `json:"portRanges,omitempty" tf:"port_ranges,omitempty"`

	// Describes the type of Service. The accepted values are
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type PortRangesInitParameters struct {

	// (Updatable) The maximum port in the range (inclusive), which may be absent for a single-port range.
	MaximumPort *float64 `json:"maximumPort,omitempty" tf:"maximum_port,omitempty"`

	// (Updatable) The minimum port in the range (inclusive), or the sole port of a single-port range.
	MinimumPort *float64 `json:"minimumPort,omitempty" tf:"minimum_port,omitempty"`
}

type PortRangesObservation struct {

	// (Updatable) The maximum port in the range (inclusive), which may be absent for a single-port range.
	MaximumPort *float64 `json:"maximumPort,omitempty" tf:"maximum_port,omitempty"`

	// (Updatable) The minimum port in the range (inclusive), or the sole port of a single-port range.
	MinimumPort *float64 `json:"minimumPort,omitempty" tf:"minimum_port,omitempty"`
}

type PortRangesParameters struct {

	// (Updatable) The maximum port in the range (inclusive), which may be absent for a single-port range.
	// +kubebuilder:validation:Optional
	MaximumPort *float64 `json:"maximumPort,omitempty" tf:"maximum_port,omitempty"`

	// (Updatable) The minimum port in the range (inclusive), or the sole port of a single-port range.
	// +kubebuilder:validation:Optional
	MinimumPort *float64 `json:"minimumPort" tf:"minimum_port,omitempty"`
}

// FirewallNetworkFirewallPolicyServiceSpec defines the desired state of FirewallNetworkFirewallPolicyService
type FirewallNetworkFirewallPolicyServiceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FirewallNetworkFirewallPolicyServiceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FirewallNetworkFirewallPolicyServiceInitParameters `json:"initProvider,omitempty"`
}

// FirewallNetworkFirewallPolicyServiceStatus defines the observed state of FirewallNetworkFirewallPolicyService.
type FirewallNetworkFirewallPolicyServiceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FirewallNetworkFirewallPolicyServiceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FirewallNetworkFirewallPolicyService is the Schema for the FirewallNetworkFirewallPolicyServices API. Provides the Network Firewall Policy Service resource in Oracle Cloud Infrastructure Network Firewall service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type FirewallNetworkFirewallPolicyService struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkFirewallPolicyId) || (has(self.initProvider) && has(self.initProvider.networkFirewallPolicyId))",message="spec.forProvider.networkFirewallPolicyId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.portRanges) || (has(self.initProvider) && has(self.initProvider.portRanges))",message="spec.forProvider.portRanges is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   FirewallNetworkFirewallPolicyServiceSpec   `json:"spec"`
	Status FirewallNetworkFirewallPolicyServiceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FirewallNetworkFirewallPolicyServiceList contains a list of FirewallNetworkFirewallPolicyServices
type FirewallNetworkFirewallPolicyServiceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FirewallNetworkFirewallPolicyService `json:"items"`
}

// Repository type metadata.
var (
	FirewallNetworkFirewallPolicyService_Kind             = "FirewallNetworkFirewallPolicyService"
	FirewallNetworkFirewallPolicyService_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FirewallNetworkFirewallPolicyService_Kind}.String()
	FirewallNetworkFirewallPolicyService_KindAPIVersion   = FirewallNetworkFirewallPolicyService_Kind + "." + CRDGroupVersion.String()
	FirewallNetworkFirewallPolicyService_GroupVersionKind = CRDGroupVersion.WithKind(FirewallNetworkFirewallPolicyService_Kind)
)

func init() {
	SchemeBuilder.Register(&FirewallNetworkFirewallPolicyService{}, &FirewallNetworkFirewallPolicyServiceList{})
}
