/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type FirewallNetworkFirewallPolicyMappedSecretInitParameters struct {

	// Unique Network Firewall Policy identifier
	NetworkFirewallPolicyID *string `json:"networkFirewallPolicyId,omitempty" tf:"network_firewall_policy_id,omitempty"`

	// Source of the secrets, where the secrets are stored. The only accepted value is OCI_VAULT
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Type of the secrets mapped based on the policy.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) OCID for the Vault Secret to be used.
	VaultSecretID *string `json:"vaultSecretId,omitempty" tf:"vault_secret_id,omitempty"`

	// (Updatable) Version number of the secret to be used.
	VersionNumber *float64 `json:"versionNumber,omitempty" tf:"version_number,omitempty"`
}

type FirewallNetworkFirewallPolicyMappedSecretObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Unique Network Firewall Policy identifier
	NetworkFirewallPolicyID *string `json:"networkFirewallPolicyId,omitempty" tf:"network_firewall_policy_id,omitempty"`

	// OCID of the Network Firewall Policy this Mapped Secret belongs to.
	ParentResourceID *string `json:"parentResourceId,omitempty" tf:"parent_resource_id,omitempty"`

	// Source of the secrets, where the secrets are stored. The only accepted value is OCI_VAULT
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Type of the secrets mapped based on the policy.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) OCID for the Vault Secret to be used.
	VaultSecretID *string `json:"vaultSecretId,omitempty" tf:"vault_secret_id,omitempty"`

	// (Updatable) Version number of the secret to be used.
	VersionNumber *float64 `json:"versionNumber,omitempty" tf:"version_number,omitempty"`
}

type FirewallNetworkFirewallPolicyMappedSecretParameters struct {

	// Unique Network Firewall Policy identifier
	// +kubebuilder:validation:Optional
	NetworkFirewallPolicyID *string `json:"networkFirewallPolicyId,omitempty" tf:"network_firewall_policy_id,omitempty"`

	// Source of the secrets, where the secrets are stored. The only accepted value is OCI_VAULT
	// +kubebuilder:validation:Optional
	Source *string `json:"source,omitempty" tf:"source,omitempty"`

	// Type of the secrets mapped based on the policy.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// (Updatable) OCID for the Vault Secret to be used.
	// +kubebuilder:validation:Optional
	VaultSecretID *string `json:"vaultSecretId,omitempty" tf:"vault_secret_id,omitempty"`

	// (Updatable) Version number of the secret to be used.
	// +kubebuilder:validation:Optional
	VersionNumber *float64 `json:"versionNumber,omitempty" tf:"version_number,omitempty"`
}

// FirewallNetworkFirewallPolicyMappedSecretSpec defines the desired state of FirewallNetworkFirewallPolicyMappedSecret
type FirewallNetworkFirewallPolicyMappedSecretSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FirewallNetworkFirewallPolicyMappedSecretParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FirewallNetworkFirewallPolicyMappedSecretInitParameters `json:"initProvider,omitempty"`
}

// FirewallNetworkFirewallPolicyMappedSecretStatus defines the observed state of FirewallNetworkFirewallPolicyMappedSecret.
type FirewallNetworkFirewallPolicyMappedSecretStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FirewallNetworkFirewallPolicyMappedSecretObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// FirewallNetworkFirewallPolicyMappedSecret is the Schema for the FirewallNetworkFirewallPolicyMappedSecrets API. Provides the Network Firewall Policy Mapped Secret resource in Oracle Cloud Infrastructure Network Firewall service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type FirewallNetworkFirewallPolicyMappedSecret struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkFirewallPolicyId) || (has(self.initProvider) && has(self.initProvider.networkFirewallPolicyId))",message="spec.forProvider.networkFirewallPolicyId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.source) || (has(self.initProvider) && has(self.initProvider.source))",message="spec.forProvider.source is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vaultSecretId) || (has(self.initProvider) && has(self.initProvider.vaultSecretId))",message="spec.forProvider.vaultSecretId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.versionNumber) || (has(self.initProvider) && has(self.initProvider.versionNumber))",message="spec.forProvider.versionNumber is a required parameter"
	Spec   FirewallNetworkFirewallPolicyMappedSecretSpec   `json:"spec"`
	Status FirewallNetworkFirewallPolicyMappedSecretStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FirewallNetworkFirewallPolicyMappedSecretList contains a list of FirewallNetworkFirewallPolicyMappedSecrets
type FirewallNetworkFirewallPolicyMappedSecretList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FirewallNetworkFirewallPolicyMappedSecret `json:"items"`
}

// Repository type metadata.
var (
	FirewallNetworkFirewallPolicyMappedSecret_Kind             = "FirewallNetworkFirewallPolicyMappedSecret"
	FirewallNetworkFirewallPolicyMappedSecret_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FirewallNetworkFirewallPolicyMappedSecret_Kind}.String()
	FirewallNetworkFirewallPolicyMappedSecret_KindAPIVersion   = FirewallNetworkFirewallPolicyMappedSecret_Kind + "." + CRDGroupVersion.String()
	FirewallNetworkFirewallPolicyMappedSecret_GroupVersionKind = CRDGroupVersion.WithKind(FirewallNetworkFirewallPolicyMappedSecret_Kind)
)

func init() {
	SchemeBuilder.Register(&FirewallNetworkFirewallPolicyMappedSecret{}, &FirewallNetworkFirewallPolicyMappedSecretList{})
}
