/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CatalogServiceCatalogAssociationInitParameters struct {

	// Identifier of the entity being associated with service catalog.
	EntityID *string `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// The type of the entity that is associated with the service catalog.
	EntityType *string `json:"entityType,omitempty" tf:"entity_type,omitempty"`

	// Identifier of the service catalog.
	ServiceCatalogID *string `json:"serviceCatalogId,omitempty" tf:"service_catalog_id,omitempty"`
}

type CatalogServiceCatalogAssociationObservation struct {

	// Identifier of the entity being associated with service catalog.
	EntityID *string `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// The type of the entity that is associated with the service catalog.
	EntityType *string `json:"entityType,omitempty" tf:"entity_type,omitempty"`

	// Identifier of the association.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Identifier of the service catalog.
	ServiceCatalogID *string `json:"serviceCatalogId,omitempty" tf:"service_catalog_id,omitempty"`

	// Timestamp of when the resource was associated with service catalog.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`
}

type CatalogServiceCatalogAssociationParameters struct {

	// Identifier of the entity being associated with service catalog.
	// +kubebuilder:validation:Optional
	EntityID *string `json:"entityId,omitempty" tf:"entity_id,omitempty"`

	// The type of the entity that is associated with the service catalog.
	// +kubebuilder:validation:Optional
	EntityType *string `json:"entityType,omitempty" tf:"entity_type,omitempty"`

	// Identifier of the service catalog.
	// +kubebuilder:validation:Optional
	ServiceCatalogID *string `json:"serviceCatalogId,omitempty" tf:"service_catalog_id,omitempty"`
}

// CatalogServiceCatalogAssociationSpec defines the desired state of CatalogServiceCatalogAssociation
type CatalogServiceCatalogAssociationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CatalogServiceCatalogAssociationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CatalogServiceCatalogAssociationInitParameters `json:"initProvider,omitempty"`
}

// CatalogServiceCatalogAssociationStatus defines the observed state of CatalogServiceCatalogAssociation.
type CatalogServiceCatalogAssociationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CatalogServiceCatalogAssociationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CatalogServiceCatalogAssociation is the Schema for the CatalogServiceCatalogAssociations API. Provides the Service Catalog Association resource in Oracle Cloud Infrastructure Service Catalog service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type CatalogServiceCatalogAssociation struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entityId) || (has(self.initProvider) && has(self.initProvider.entityId))",message="spec.forProvider.entityId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.serviceCatalogId) || (has(self.initProvider) && has(self.initProvider.serviceCatalogId))",message="spec.forProvider.serviceCatalogId is a required parameter"
	Spec   CatalogServiceCatalogAssociationSpec   `json:"spec"`
	Status CatalogServiceCatalogAssociationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CatalogServiceCatalogAssociationList contains a list of CatalogServiceCatalogAssociations
type CatalogServiceCatalogAssociationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CatalogServiceCatalogAssociation `json:"items"`
}

// Repository type metadata.
var (
	CatalogServiceCatalogAssociation_Kind             = "CatalogServiceCatalogAssociation"
	CatalogServiceCatalogAssociation_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CatalogServiceCatalogAssociation_Kind}.String()
	CatalogServiceCatalogAssociation_KindAPIVersion   = CatalogServiceCatalogAssociation_Kind + "." + CRDGroupVersion.String()
	CatalogServiceCatalogAssociation_GroupVersionKind = CRDGroupVersion.WithKind(CatalogServiceCatalogAssociation_Kind)
)

func init() {
	SchemeBuilder.Register(&CatalogServiceCatalogAssociation{}, &CatalogServiceCatalogAssociationList{})
}
